### ISSUE TITLE
Model has low TPU utilization

### ISSUE THREAD

**Issue by cffan** [pytorch/xla#1989]
## ❓ Questions and Help
I'm trying to run a variant of this [model](https://github.com/stelzner/monet) on TPU v3-8. It's a combination of UNet and CNN. However the TPU usage seems to be very low:

```
TPU type: TPU v3\n  Number of TPU cores: 1 (Replica count = 1, num cores per replica = 1)\n  Per-core batch size: 128\n  TPU idle time (lower is better): 0.001%\n  Utilization of TPU Matrix Units (higher is better): 1.59%\n  Step time: 342ms (avg), 342ms (min), 342ms (max)\n  Infeed percentage: 0.008% (avg), 0.008% (min), 0.008% (max)\n\n
```

Looking at the metrics, I don't see things prefixed with aten:: and the compile time is constant after the first two steps. Could you help me understand why the usage is low and is there way to improve it?

```
[MetricsData; step=0]
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 01m02s239ms231.349us
  Percentiles: 1%=01m02s239ms231.349us; 5%=01m02s239ms231.349us; 10%=01m02s239ms231.349us; 20%=01m02s239ms231.349us; 50%=01m02s239ms231.349us; 80%=01m02s239ms231.349us; 90%=01m02s239ms231.349us; 95%=01m02s239ms231.349us; 99%=01m02s239ms231.349us
Metric: DeviceLockWait
  TotalSamples: 1
  Accumulator: 004.709us
  Percentiles: 1%=004.709us; 5%=004.709us; 10%=004.709us; 20%=004.709us; 50%=004.709us; 80%=004.709us; 90%=004.709us; 95%=004.709us; 99%=004.709us
Metric: InputOutputAliasCount
  TotalSamples: 1
  Accumulator: 340.00
  Percentiles: 1%=340.00; 5%=340.00; 10%=340.00; 20%=340.00; 50%=340.00; 80%=340.00; 90%=340.00; 95%=340.00; 99%=340.00
Metric: IrValueTensorToXlaData
  TotalSamples: 100
  Accumulator: 01s098ms380.932us
  ValueRate: 301ms176.246us / second
  Rate: 27.42 / second
  Percentiles: 1%=001ms144.321us; 5%=001ms281.021us; 10%=001ms327.308us; 20%=001ms396.094us; 50%=002ms672.558us; 80%=006ms336.472us; 90%=012ms174.731us; 95%=054ms841.442us; 99%=419ms214.307us
Metric: OutboundData
  TotalSamples: 116
  Accumulator: 152.30MB
  ValueRate: 36.66MB / second
  Rate: 27.9243 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=128.00B; 50%=256.00B; 80%=20.25KB; 90%=576.00KB; 95%=9.00MB; 99%=18.00MB
Metric: TensorsGraphSize
  TotalSamples: 1
  Accumulator: 55837.00
  Percentiles: 1%=55837.00; 5%=55837.00; 10%=55837.00; 20%=55837.00; 50%=55837.00; 80%=55837.00; 90%=55837.00; 95%=55837.00; 99%=55837.00
Metric: TransferToServerTime
  TotalSamples: 116
  Accumulator: 01s162ms294.998us
  ValueRate: 280ms095.667us / second
  Rate: 27.9543 / second
  Percentiles: 1%=001ms138.529us; 5%=001ms273.513us; 10%=001ms320.955us; 20%=001ms435.977us; 50%=002ms834.639us; 80%=006ms303.683us; 90%=010ms794.809us; 95%=037ms797.696us; 99%=093ms917.762us
Metric: TransferToServerTransformTime
  TotalSamples: 116
  Accumulator: 122ms417.369us
  ValueRate: 029ms468.941us / second
  Rate: 27.9241 / second
  Percentiles: 1%=076.630us; 5%=086.185us; 10%=093.509us; 20%=100.820us; 50%=135.404us; 80%=341.712us; 90%=001ms016.716us; 95%=002ms886.520us; 99%=010ms883.446us
Counter: CreateCompileHandles
  Value: 1
Counter: CreateDataHandles
  Value: 116
Counter: CreateXlaTensor
  Value: 28067
Counter: DestroyXlaTensor
  Value: 27727
Counter: MarkStep
  Value: 1
Counter: UncachedCompile
  Value: 1
Counter: XRTAllocateFromTensor_Empty
  Value: 39
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 2
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_log_softmax
  Value: 1
Counter: xla::_log_softmax_backward_data
  Value: 1
Counter: xla::_s_where
  Value: 1
Counter: xla::add
  Value: 12579
Counter: xla::add_
  Value: 157
Counter: xla::addcdiv_
  Value: 76
Counter: xla::addcmul_
  Value: 76
Counter: xla::addmm
  Value: 10
Counter: xla::as_strided
  Value: 138
Counter: xla::cat
  Value: 44
Counter: xla::clamp_min
  Value: 5
Counter: xla::clone
  Value: 15
Counter: xla::convolution_backward_overrideable
  Value: 97
Counter: xla::convolution_overrideable
  Value: 97
Counter: xla::copy_
  Value: 160
Counter: xla::div
  Value: 91
Counter: xla::empty
  Value: 389
Counter: xla::empty_strided
  Value: 123
Counter: xla::eq
  Value: 1
Counter: xla::exp
  Value: 16
Counter: xla::expand
  Value: 28
Counter: xla::fill_
  Value: 1
Counter: xla::ge
  Value: 5
Counter: xla::gt
  Value: 1
Counter: xla::kl_div
  Value: 1
Counter: xla::kl_div_backward
  Value: 1
Counter: xla::log
  Value: 7
Counter: xla::log_sigmoid_backward
  Value: 8
Counter: xla::log_sigmoid_forward
  Value: 8
Counter: xla::logsumexp
  Value: 1
Counter: xla::masked_fill_
  Value: 1
Counter: xla::mean
  Value: 1
Counter: xla::mm
  Value: 20
Counter: xla::mul
  Value: 97
Counter: xla::mul_
  Value: 152
Counter: xla::native_batch_norm
  Value: 88
Counter: xla::native_batch_norm_backward
  Value: 88
Counter: xla::neg
  Value: 35
Counter: xla::normal_
  Value: 5
Counter: xla::pow
  Value: 25
Counter: xla::relu
  Value: 73
Counter: xla::relu_
  Value: 20
Counter: xla::repeat
  Value: 96
Counter: xla::select
  Value: 20
Counter: xla::slice
  Value: 98
Counter: xla::split
  Value: 106
Counter: xla::sqrt
  Value: 76
Counter: xla::sub
  Value: 27
Counter: xla::sub_
  Value: 1
Counter: xla::sum
  Value: 27
Counter: xla::t
  Value: 40
Counter: xla::threshold_backward
  Value: 93
Counter: xla::unsqueeze
  Value: 7
Counter: xla::upsample_nearest2d
  Value: 40
Counter: xla::upsample_nearest2d_backward
  Value: 40
Counter: xla::view
  Value: 257
Counter: xla::zero_
  Value: 165
Metric: XrtAllocateFromTensor
  TotalSamples: 11726
  Accumulator: 01m01s614ms980.392us
  Mean: 004ms436.670us
  StdDev: 006ms201.867us
  Rate: 1.48636 / second
  Percentiles: 25%=444.232us; 50%=002ms312.764us; 80%=004ms231.323us; 90%=017ms992.306us; 95%=020ms812.658us; 99%=021ms523.514us
Metric: XrtCompile
  TotalSamples: 83
  Accumulator: 10m29s134ms746.392us
  Mean: 08s580ms924.655us
  StdDev: 20s200ms251.922us
  Rate: 0.0192617 / second
  Percentiles: 25%=223.129us; 50%=141ms367.622us; 80%=297ms677.068us; 90%=60s602ms064.245us; 95%=01m01s376ms662.870us; 99%=01m07s588ms858.992us
Metric: XrtExecute
  TotalSamples: 2590
  Accumulator: 14m43s183ms171.999us
  Mean: 319ms265.785us
  StdDev: 087ms227.252us
  Rate: 0.506904 / second
  Percentiles: 25%=347ms868.277us; 50%=347ms136.273us; 80%=347ms402.232us; 90%=348ms615.608us; 95%=348ms805.470us; 99%=358ms305.610us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 360
  Accumulator: 349ms719.725us
  Mean: 968.666us
  StdDev: 764.103us
  Rate: 0.0969982 / second
  Percentiles: 25%=477.261us; 50%=731.151us; 80%=001ms205.448us; 90%=003ms563.014us; 95%=003ms829.869us; 99%=003ms297.894us
Metric: XrtReleaseAllocation
  TotalSamples: 70902
  Accumulator: 12s352ms366.363us
  Mean: 152.066us
  StdDev: 250.491us
  Rate: 38.086 / second
  Percentiles: 25%=011.291us; 50%=032.794us; 80%=237.156us; 90%=527.764us; 95%=760.225us; 99%=001ms100.623us

[MetricsData; step=1]
Metric: CompileTime
  TotalSamples: 2
  Accumulator: 02m05s043ms502.824us
  ValueRate: 02s763ms266.096us / second
  Rate: 0.0282027 / second
  Percentiles: 1%=01m02s239ms231.349us; 5%=01m02s239ms231.349us; 10%=01m02s239ms231.349us; 20%=01m02s239ms231.349us; 50%=01m03s803ms271.475us; 80%=01m03s803ms271.475us; 90%=01m03s803ms271.475us; 95%=01m03s803ms271.475us; 99%=01m03s803ms271.475us
Metric: DeviceLockWait
  TotalSamples: 2
  Accumulator: 008.329us
  ValueRate: 000.118us / second
  Rate: 0.0282193 / second
  Percentiles: 1%=003.620us; 5%=003.620us; 10%=003.620us; 20%=003.620us; 50%=004.709us; 80%=004.709us; 90%=004.709us; 95%=004.709us; 99%=004.709us
Metric: ExecuteTime
  TotalSamples: 1
  Accumulator: 451ms833.983us
  Percentiles: 1%=451ms833.983us; 5%=451ms833.983us; 10%=451ms833.983us; 20%=451ms833.983us; 50%=451ms833.983us; 80%=451ms833.983us; 90%=451ms833.983us; 95%=451ms833.983us; 99%=451ms833.983us
Metric: InputOutputAliasCount
  TotalSamples: 2
  Accumulator: 675.00
  ValueRate: 9.59 / second
  Rate: 0.0284271 / second
  Percentiles: 1%=335.00; 5%=335.00; 10%=335.00; 20%=335.00; 50%=340.00; 80%=340.00; 90%=340.00; 95%=340.00; 99%=340.00
Metric: IrValueTensorToXlaData
  TotalSamples: 103
  Accumulator: 02s844ms452.711us
  ValueRate: 025ms681.276us / second
  Rate: 1.37828 / second
  Percentiles: 1%=001ms144.321us; 5%=001ms281.021us; 10%=001ms327.308us; 20%=001ms396.094us; 50%=002ms712.553us; 80%=007ms705.862us; 90%=017ms506.480us; 95%=079ms534.706us; 99%=419ms214.307us
Metric: OutboundData
  TotalSamples: 121
  Accumulator: 246.30MB
  ValueRate: 3.28MB / second
  Rate: 1.6121 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=64.00B; 50%=256.00B; 80%=36.00KB; 90%=1.12MB; 95%=10.00MB; 99%=70.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 11
  Accumulator: 02s452ms568.608us
  ValueRate: 03s367ms263.514us / second
  Rate: 15.1087 / second
  Percentiles: 1%=002ms084.286us; 5%=002ms084.286us; 10%=023ms847.954us; 20%=253ms003.214us; 50%=253ms460.487us; 80%=292ms594.648us; 90%=296ms357.628us; 95%=318ms011.036us; 99%=318ms011.036us
Metric: TensorsGraphSize
  TotalSamples: 2
  Accumulator: 111234.00
  ValueRate: 1568.51 / second
  Rate: 0.028202 / second
  Percentiles: 1%=55397.00; 5%=55397.00; 10%=55397.00; 20%=55397.00; 50%=55837.00; 80%=55837.00; 90%=55837.00; 95%=55837.00; 99%=55837.00
Metric: TransferToServerTime
  TotalSamples: 121
  Accumulator: 02s912ms162.692us
  ValueRate: 025ms477.526us / second
  Rate: 1.6122 / second
  Percentiles: 1%=001ms138.529us; 5%=001ms281.579us; 10%=001ms341.747us; 20%=001ms442.894us; 50%=002ms862.023us; 80%=006ms353.463us; 90%=014ms294.560us; 95%=054ms812.155us; 99%=419ms170.494us
Metric: TransferToServerTransformTime
  TotalSamples: 121
  Accumulator: 145ms751.517us
  ValueRate: 002ms928.538us / second
  Rate: 1.61209 / second
  Percentiles: 1%=076.630us; 5%=088.327us; 10%=094.181us; 20%=101.640us; 50%=145.586us; 80%=372.850us; 90%=002ms652.791us; 95%=004ms886.412us; 99%=015ms650.928us
Counter: CreateCompileHandles
  Value: 2
Counter: CreateDataHandles
  Value: 461
Counter: CreateXlaTensor
  Value: 55772
Counter: DestroyDataHandles
  Value: 183
Counter: DestroyXlaTensor
  Value: 55432
Counter: MarkStep
  Value: 2
Counter: ReleaseDataHandles
  Value: 183
Counter: UncachedCompile
  Value: 2
Counter: XRTAllocateFromTensor_Empty
  Value: 39
Counter: XrtCompile_Empty
  Value: 1152
Counter: XrtExecuteChained_Empty
  Value: 1152
Counter: XrtExecute_Empty
  Value: 1152
Counter: XrtRead_Empty
  Value: 1152
Counter: XrtReleaseAllocationHandle_Empty
  Value: 1152
Counter: XrtReleaseCompileHandle_Empty
  Value: 1152
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 1152
Counter: xla::_log_softmax
  Value: 2
Counter: xla::_log_softmax_backward_data
  Value: 2
Counter: xla::_s_where
  Value: 2
Counter: xla::add
  Value: 25158
Counter: xla::add_
  Value: 390
Counter: xla::addcdiv_
  Value: 152
Counter: xla::addcmul_
  Value: 152
Counter: xla::addmm
  Value: 20
Counter: xla::as_strided
  Value: 171
Counter: xla::cat
  Value: 88
Counter: xla::clamp_min
  Value: 10
Counter: xla::clone
  Value: 30
Counter: xla::convolution_backward_overrideable
  Value: 194
Counter: xla::convolution_overrideable
  Value: 194
Counter: xla::copy_
  Value: 215
Counter: xla::div
  Value: 182
Counter: xla::empty
  Value: 521
Counter: xla::empty_strided
  Value: 141
Counter: xla::eq
  Value: 2
Counter: xla::exp
  Value: 32
Counter: xla::expand
  Value: 56
Counter: xla::fill_
  Value: 2
Counter: xla::ge
  Value: 10
Counter: xla::gt
  Value: 2
Counter: xla::kl_div
  Value: 2
Counter: xla::kl_div_backward
  Value: 2
Counter: xla::log
  Value: 14
Counter: xla::log_sigmoid_backward
  Value: 16
Counter: xla::log_sigmoid_forward
  Value: 16
Counter: xla::logsumexp
  Value: 2
Counter: xla::masked_fill_
  Value: 2
Counter: xla::mean
  Value: 2
Counter: xla::mm
  Value: 40
Counter: xla::mul
  Value: 194
Counter: xla::mul_
  Value: 304
Counter: xla::native_batch_norm
  Value: 176
Counter: xla::native_batch_norm_backward
  Value: 176
Counter: xla::neg
  Value: 70
Counter: xla::normal_
  Value: 10
Counter: xla::pow
  Value: 50
Counter: xla::relu
  Value: 146
Counter: xla::relu_
  Value: 40
Counter: xla::repeat
  Value: 192
Counter: xla::select
  Value: 40
Counter: xla::slice
  Value: 196
Counter: xla::split
  Value: 212
Counter: xla::sqrt
  Value: 152
Counter: xla::sub
  Value: 54
Counter: xla::sub_
  Value: 2
Counter: xla::sum
  Value: 54
Counter: xla::t
  Value: 80
Counter: xla::threshold_backward
  Value: 186
Counter: xla::unsqueeze
  Value: 14
Counter: xla::upsample_nearest2d
  Value: 80
Counter: xla::upsample_nearest2d_backward
  Value: 80
Counter: xla::view
  Value: 514
Counter: xla::zero_
  Value: 254
Metric: XrtAllocateFromTensor
  TotalSamples: 11731
  Accumulator: 01m01s644ms089.488us
  Mean: 004ms437.275us
  StdDev: 006ms205.065us
  Rate: 1.34955 / second
  Percentiles: 25%=443.568us; 50%=002ms312.764us; 80%=004ms231.323us; 90%=017ms992.306us; 95%=020ms812.658us; 99%=021ms564.726us
Metric: XrtCompile
  TotalSamples: 84
  Accumulator: 12m31s362ms395.981us
  Mean: 08s231ms504.714us
  StdDev: 21s936ms154.226us
  Rate: 0.0191782 / second
  Percentiles: 25%=226.359us; 50%=142ms537.150us; 80%=300ms221.513us; 90%=60s921ms139.375us; 95%=01m02s587ms376.008us; 99%=01m07s588ms858.992us
Metric: XrtExecute
  TotalSamples: 2591
  Accumulator: 14m44s619ms764.785us
  Mean: 319ms351.971us
  StdDev: 087ms298.518us
  Rate: 0.426901 / second
  Percentiles: 25%=347ms868.277us; 50%=347ms136.273us; 80%=347ms404.823us; 90%=348ms616.662us; 95%=348ms805.950us; 99%=358ms393.251us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 360
  Accumulator: 349ms719.725us
  Mean: 968.666us
  StdDev: 764.103us
  Rate: 0.0969982 / second
  Percentiles: 25%=477.261us; 50%=731.151us; 80%=001ms205.448us; 90%=003ms563.014us; 95%=003ms829.869us; 99%=003ms297.894us
Metric: XrtReleaseAllocation
  TotalSamples: 70913
  Accumulator: 12s353ms982.956us
  Mean: 148.086us
  StdDev: 247.424us
  Rate: 2.15616 / second
  Percentiles: 25%=011.291us; 50%=032.239us; 80%=211.121us; 90%=512.096us; 95%=742.111us; 99%=001ms100.623us
```

[debug.tar.gz](https://drive.google.com/file/d/1aDv8NJGzvrUX9qw6XWnEscOeP80ZzLv6/view?usp=sharing)
