### ISSUE TITLE
Stops Execution after a single epoch

### ISSUE THREAD

**Issue by sambaths** [pytorch/xla#2176]
Hi,
When I tried running a training code in colab, the execution stops after a single epoch.
It puts out the following error. 

Error:
```
06:43:14.636825: E tensorflow/compiler/xla/xla_client/tf_logging.cc:11] Check failed: xtensor 
*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	torch_xla::bridge::GetXlaTensor(at::Tensor const&)
	torch_xla::AtenXlaType::native_batch_norm_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, std::array<bool, 3ul>)
	c10::detail::wrap_kernel_functor_unboxed_<c10::detail::WrapRuntimeKernelFunctor_<std::tuple<at::Tensor, at::Tensor, at::Tensor> (*)(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, std::array<bool, 3ul>), std::tuple<at::Tensor, at::Tensor, at::Tensor>, c10::guts::typelist::typelist<at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, std::array<bool, 3ul> > >, std::tuple<at::Tensor, at::Tensor, at::Tensor> (at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, std::array<bool, 3ul>)>::call(c10::OperatorKernel*, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, bool, double, std::array<bool, 3ul>)
	
	
	
	
	
	
	torch::autograd::generated::NativeBatchNormBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&)
	
	torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&)
	torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool)
	torch::autograd::Engine::thread_init(int)
	torch::autograd::python::PythonEngine::thread_init(int)
	
	
	clone
*** End stack trace ***
Input tensor is not an XLA tensor: UndefinedType

```

Metrics Report:
```
Metric: XrtAllocateFromTensor
  TotalSamples: 199
  Accumulator: 01s146ms742.795us
  Mean: 006ms757.501us
  StdDev: 028ms427.271us
  Rate: 1.2319 / second
  Percentiles: 25%=365.848us; 50%=540.345us; 80%=004ms605.823us; 90%=008ms641.468us; 95%=021ms863.361us; 99%=277ms194.183us
Metric: XrtCompile
  TotalSamples: 11
  Accumulator: 01m16s279ms801.057us
  Mean: 07s934ms436.460us
  StdDev: 05s897ms938.901us
  Rate: 0.0762926 / second
  Percentiles: 25%=02s987ms858.165us; 50%=07s076ms800.448us; 80%=09s849ms662.753us; 90%=14s465ms247.179us; 95%=16s739ms011.065us; 99%=16s739ms011.065us
Metric: XrtExecute
  TotalSamples: 55
  Accumulator: 08s226ms345.901us
  Mean: 150ms569.925us
  StdDev: 177ms447.483us
  Rate: 0.381501 / second
  Percentiles: 25%=018ms446.528us; 50%=136ms233.754us; 80%=211ms078.858us; 90%=511ms636.353us; 95%=511ms007.228us; 99%=537ms883.373us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 343
  Accumulator: 01m12s313ms705.432us
  Mean: 211ms824.214us
  StdDev: 239ms831.144us
  Rate: 2.37932 / second
  Percentiles: 25%=002ms071.271us; 50%=106ms056.534us; 80%=422ms655.840us; 90%=576ms815.643us; 95%=643ms162.778us; 99%=787ms670.561us
Metric: XrtReleaseAllocation
  TotalSamples: 360
  Accumulator: 032ms250.315us
  Mean: 089.584us
  StdDev: 155.925us
  Rate: 2.49737 / second
  Percentiles: 25%=011.634us; 50%=026.457us; 80%=100.351us; 90%=306.635us; 95%=479.364us; 99%=812.498us
```
If you need to look the code I used for training.
[train.py](https://github.com/sambaths/ChromaGAN_PyTorch/blob/master/src/train.py)
The related files can be found in the same repo.
