### ISSUE TITLE
PyTorch XLA is very slow on Google Colab

### ISSUE THREAD

**Issue by bjourne** [pytorch/xla#2247]
Training a network on Google Colab with PyTorch XLA and with eight TPUs is about 10 times slower than using the GPU and no XLA. This is unexpected. Shouldn't XLA make training much faster?

Here is the training loop of my program which is based on the [PyTorch on Cloud TPUs: MultiCore Training AlexNet on Fashion MNIST](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/multi-core-alexnet-fashion-mnist.ipynb) notebook:

```python
    for i in range(3):
        start = time()
        loader = ParallelLoader(train_loader, [dev]) \
            .per_device_loader(dev)
        state = model.init_state(batch_size, dev)
        model.train()
        for x, y in loader:
            opt.zero_grad()
            state = [s.detach() for s in state]
            y_hat, state = model(x, state)
            loss = crit(y_hat, y.reshape(-1))
            loss.backward()
            optimizer_step(opt)
        elapsed = time() - start
        master_print('%.2f seconds for %d batches.'
                     % (elapsed, len(train_ds)))
```
Each epoch takes about 140 seconds. An equivalent program running on Google Colab with a GPU takes 20 seconds per epoch. Here is a self-contained gist demonstrating the slowness. https://gist.github.com/bjourne/0cc9ae5729ab78ce0c7765a5c5a207c0 It uses the observations package for the Penn Treebank dataset.

**Comment by btomtom5** [comment]
For easier debugging, I added a metrics report. This was taken at the very last epoch. In this case I ran it for 20 epochs. Slight tangent, but what does XRT<metric_name> mean? I found that XRT is the communication layer between the XLA device and python, but what is the difference between CompileTime and XRTCompile or ExecuteTime and XRTExecute? Thanks! 
```
Metric: CompileTime
  TotalSamples: 4
  Accumulator: 04s589ms590.974us
  ValueRate: 023ms960.897us / second
  Rate: 0.0255932 / second
  Percentiles: 1%=024ms320.066us; 5%=024ms320.066us; 10%=024ms320.066us; 20%=024ms320.066us; 50%=02s720ms247.948us; 80%=02s746ms660.403us; 90%=02s746ms660.403us; 95%=02s746ms660.403us; 99%=02s746ms660.403us
Metric: DeviceLockWait
  TotalSamples: 1122
  Accumulator: 003ms174.641us
  ValueRate: 001.328us / second
  Rate: 0.468417 / second
  Percentiles: 1%=001.701us; 5%=002.097us; 10%=002.230us; 20%=002.349us; 50%=002.587us; 80%=002.903us; 90%=003.121us; 95%=003.431us; 99%=011.410us
Metric: ExecuteTime
  TotalSamples: 1121
  Accumulator: 03m04s242ms643.649us
  ValueRate: 076ms890.245us / second
  Rate: 0.468365 / second
  Percentiles: 1%=054ms856.143us; 5%=054ms447.633us; 10%=055ms898.424us; 20%=063ms551.695us; 50%=145ms486.663us; 80%=241ms377.513us; 90%=294ms087.724us; 95%=340ms904.275us; 99%=463ms020.880us
Metric: InputOutputAliasCount
  TotalSamples: 4
  Accumulator: 51.00
  ValueRate: 0.33 / second
  Rate: 0.0256053 / second
  Percentiles: 1%=2.00; 5%=2.00; 10%=2.00; 20%=2.00; 50%=20.00; 80%=20.00; 90%=20.00; 95%=20.00; 99%=20.00
Metric: IrValueTensorToXlaData
  TotalSamples: 41
  Accumulator: 01s282ms455.891us
  ValueRate: 564.427us / second
  Rate: 0.0180447 / second
  Percentiles: 1%=001ms385.848us; 5%=002ms427.149us; 10%=003ms972.753us; 20%=003ms290.177us; 50%=004ms007.770us; 80%=055ms577.372us; 90%=081ms776.349us; 95%=113ms722.863us; 99%=263ms837.832us
Metric: OutboundData
  TotalSamples: 1439
  Accumulator: 179.70MB
  ValueRate: 74.63KB / second
  Rate: 0.598097 / second
  Percentiles: 1%=8.00B; 5%=8.00B; 10%=8.00B; 20%=8.00B; 50%=8.00B; 80%=160.00KB; 90%=640.00KB; 95%=640.00KB; 99%=640.00KB
Metric: ReleaseDataHandlesTime
  TotalSamples: 11372
  Accumulator: 14s950ms815.598us
  ValueRate: 006ms832.635us / second
  Rate: 5.17792 / second
  Percentiles: 1%=532.212us; 5%=626.633us; 10%=686.950us; 20%=789.423us; 50%=001ms034.373us; 80%=001ms259.645us; 90%=001ms386.729us; 95%=002ms687.614us; 99%=004ms146.956us
Metric: TensorsGraphSize
  TotalSamples: 1122
  Accumulator: 39030977.00
  ValueRate: 16303.02 / second
  Rate: 0.468414 / second
  Percentiles: 1%=10.00; 5%=35322.00; 10%=35322.00; 20%=35322.00; 50%=35322.00; 80%=35322.00; 90%=35322.00; 95%=35322.00; 99%=35322.00
Metric: TransferToServerTime
  TotalSamples: 1439
  Accumulator: 58s794ms674.254us
  ValueRate: 022ms450.591us / second
  Rate: 0.5981 / second
  Percentiles: 1%=002ms723.752us; 5%=002ms020.673us; 10%=002ms265.361us; 20%=003ms958.835us; 50%=019ms916.308us; 80%=058ms724.968us; 90%=105ms078.122us; 95%=150ms419.519us; 99%=240ms860.630us
Metric: TransferToServerTransformTime
  TotalSamples: 1439
  Accumulator: 07s085ms968.392us
  ValueRate: 003ms932.982us / second
  Rate: 0.598097 / second
  Percentiles: 1%=045.284us; 5%=053.907us; 10%=058.274us; 20%=071.031us; 50%=608.921us; 80%=008ms690.258us; 90%=014ms419.274us; 95%=020ms009.037us; 99%=045ms886.820us
Counter: CachedCompile
  Value: 1118
Counter: CreateCompileHandles
  Value: 4
Counter: CreateDataHandles
  Value: 25481
Counter: CreateXlaTensor
  Value: 18432587
Counter: DestroyDataHandles
  Value: 25465
Counter: DestroyXlaTensor
  Value: 18432565
Counter: DeviceDataCacheMiss
  Value: 4
Counter: MarkStep
  Value: 1122
Counter: ReleaseDataHandles
  Value: 25465
Counter: UncachedCompile
  Value: 4
Counter: XRTAllocateFromTensor_Empty
  Value: 27
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_log_softmax
  Value: 1105
Counter: xla::_log_softmax_backward_data
  Value: 1105
Counter: xla::add
  Value: 2114970
Counter: xla::add_
  Value: 722663
Counter: xla::addmm
  Value: 708305
Counter: xla::as_strided
  Value: 41
Counter: xla::bernoulli_
  Value: 1105
Counter: xla::cat
  Value: 353600
Counter: xla::copy_
  Value: 41
Counter: xla::div_
  Value: 1105
Counter: xla::embedding
  Value: 1105
Counter: xla::embedding_dense_backward
  Value: 1105
Counter: xla::empty
  Value: 2251
Counter: xla::empty_strided
  Value: 41
Counter: xla::fill_
  Value: 1105
Counter: xla::index_select
  Value: 1105
Counter: xla::mm
  Value: 1415505
Counter: xla::mul
  Value: 3183505
Counter: xla::nll_loss_backward
  Value: 1105
Counter: xla::nll_loss_forward
  Value: 1105
Counter: xla::sigmoid_
  Value: 1060800
Counter: xla::sigmoid_backward
  Value: 1060800
Counter: xla::split
  Value: 353600
Counter: xla::stack
  Value: 4420
Counter: xla::sum
  Value: 708305
Counter: xla::t
  Value: 2832115
Counter: xla::tanh
  Value: 353600
Counter: xla::tanh_
  Value: 353600
Counter: xla::tanh_backward
  Value: 707200
Counter: xla::transpose
  Value: 4420
Counter: xla::unbind
  Value: 4420
Counter: xla::view
  Value: 713830
Counter: xla::zero_
  Value: 7728
Metric: XrtAllocateFromTensor
  TotalSamples: 63362
  Accumulator: 02m10s200ms767.219us
  Mean: 002ms075.807us
  StdDev: 778.413us
  Rate: 10.7113 / second
  Percentiles: 25%=001ms284.624us; 50%=002ms308.897us; 80%=003ms772.551us; 90%=003ms972.661us; 95%=003ms168.602us; 99%=004ms576.723us
Metric: XrtCompile
  TotalSamples: 98
  Accumulator: 10m54s320ms435.111us
  Mean: 06s064ms494.236us
  StdDev: 14s570ms744.908us
  Rate: 0.0164305 / second
  Percentiles: 25%=295.375us; 50%=021ms120.028us; 80%=266ms106.709us; 90%=35s640ms945.225us; 95%=39s602ms846.919us; 99%=39s935ms726.141us
Metric: XrtExecute
  TotalSamples: 21114
  Accumulator: 01h01m43s949ms833.777us
  Mean: 169ms349.511us
  StdDev: 095ms401.243us
  Rate: 3.82357 / second
  Percentiles: 25%=097ms848.351us; 50%=157ms248.064us; 80%=242ms428.398us; 90%=290ms943.523us; 95%=342ms207.421us; 99%=453ms905.782us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReleaseAllocation
  TotalSamples: 209515
  Accumulator: 06s245ms288.928us
  Mean: 026.338us
  StdDev: 035.876us
  Rate: 44.1387 / second
  Percentiles: 25%=010.385us; 50%=015.109us; 80%=030.618us; 90%=061.331us; 95%=097.648us; 99%=190.847us
```
