### ISSUE TITLE
all_reduce in backward causes a re-compile

### ISSUE THREAD

**Issue by matt-peters** [pytorch/xla#2319]
## 🐛 Bug

I implemented an XLA version of `SyncBatchNorm` (#2223), loosely following the pytorch version (https://github.com/pytorch/pytorch/blob/541814f2b7eacabacdc87ccb1b4495bf486f501a/torch/nn/modules/_functions.py#L6).  This requires an `all_reduce` in backward (https://github.com/pytorch/pytorch/blob/541814f2b7eacabacdc87ccb1b4495bf486f501a/torch/nn/modules/_functions.py#L79).  However, I found that this forces a re-compile on each call, which makes the code unusably slow for a standard ResNet that has many batch norm layers.

## To Reproduce

Here is a minimal script to reproduce.
```python

import torch

import torch_xla.core.xla_model as xm
import torch_xla.distributed.xla_multiprocessing as xmp
import torch_xla.debug.metrics as met

from torch.autograd.function import Function

import time

class AllReduceBackward(Function):
    @staticmethod
    def forward(ctx, input, should_reduce):
        ctx.should_reduce = should_reduce
        return 5.0 * input

    @staticmethod
    def backward(ctx, grad_output):
        if ctx.should_reduce:
            reduced_grad = xm.all_reduce(xm.REDUCE_SUM, grad_output)
        else:
            reduced_grad = grad_output
        grad_input = 5.0 * reduced_grad
        return grad_input, None


def benchmark(index, should_reduce):
    xm.rendezvous('init')
    time_start = time.time()
    for k in range(10):
        last_time_start = time.time()
        x = torch.rand(128, 1024, device=xm.xla_device())

        # forward/backward
        x.requires_grad_(True)
        y = AllReduceBackward.apply(x, should_reduce)
        loss = (y ** 2).mean()
        loss.backward()
        xm.mark_step()

    if xm.is_master_ordinal():
        this_time = time.time()
        print("Metrics for should_reduce={}".format(should_reduce))
        print("Total time: ", this_time - time_start)
        print("Time for last iteration: ", this_time - last_time_start)
        print(met.metrics_report())
        print("-" * 50)


def run_benchmark(should_reduce):
    xmp.spawn(benchmark, args=(should_reduce, ), nprocs=8, start_method='spawn')


if __name__ == '__main__':
    run_benchmark(True)
    run_benchmark(False)
```

When running on a v3-8 TPU, it outputs:

```
Metrics for should_reduce=True
Total time:  0.21088099479675293
Time for last iteration:  0.013144254684448242
Metric: CompileTime
  TotalSamples: 10
  Accumulator: 067ms885.816us
  ValueRate: 377ms161.815us / second
  Rate: 56.3889 / second
  Percentiles: 1%=003ms808.219us; 5%=003ms808.219us; 10%=003ms898.512us; 20%=003ms367.656us; 50%=005ms320.894us; 80%=015ms588.378us; 90%=018ms930.982us; 95%=018ms930.982us; 99%=018ms930.982us
Metric: DeviceLockWait
  TotalSamples: 10
  Accumulator: 024ms177.447us
  ValueRate: 131ms442.502us / second
  Rate: 54.3657 / second
  Percentiles: 1%=002.298us; 5%=002.298us; 10%=002.337us; 20%=002.363us; 50%=002.651us; 80%=005ms839.521us; 90%=019ms316.709us; 95%=019ms316.709us; 99%=019ms316.709us
Metric: ExecuteTime
  TotalSamples: 9
  Accumulator: 101ms368.019us
  ValueRate: 694ms371.898us / second
  Rate: 61.6501 / second
  Percentiles: 1%=002ms241.062us; 5%=002ms241.062us; 10%=002ms241.062us; 20%=003ms949.219us; 50%=004ms828.004us; 80%=022ms751.664us; 90%=053ms964.054us; 95%=053ms964.054us; 99%=053ms964.054us
Metric: InputOutputAliasCount
  TotalSamples: 10
  Accumulator: 40.00
  ValueRate: 215.23 / second
  Rate: 53.8084 / second
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=4.00; 80%=4.00; 90%=4.00; 95%=4.00; 99%=4.00
Metric: OutboundData
  TotalSamples: 13
  Accumulator: 92.00B
  ValueRate: 472.27B / second
  Rate: 66.7343 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: ReleaseDataHandlesTime
  TotalSamples: 14
  Accumulator: 015ms474.532us
  ValueRate: 109ms563.005us / second
  Rate: 98.2183 / second
  Percentiles: 1%=529.514us; 5%=529.514us; 10%=534.521us; 20%=564.274us; 50%=641.616us; 80%=679.461us; 90%=004ms028.304us; 95%=004ms218.016us; 99%=004ms218.016us
Metric: TensorsGraphSize
  TotalSamples: 10
  Accumulator: 1335.00
  ValueRate: 7525.71 / second
  Rate: 56.3724 / second
  Percentiles: 1%=30.00; 5%=30.00; 10%=53.00; 20%=76.00; 50%=145.00; 80%=214.00; 90%=237.00; 95%=237.00; 99%=237.00
Metric: TransferToServerTime
  TotalSamples: 13
  Accumulator: 089ms667.641us
  ValueRate: 460ms179.180us / second
  Rate: 67.4691 / second
  Percentiles: 1%=001ms139.746us; 5%=001ms139.746us; 10%=001ms301.583us; 20%=001ms352.767us; 50%=003ms306.069us; 80%=004ms807.145us; 90%=007ms308.571us; 95%=053ms852.573us; 99%=053ms852.573us
Metric: TransferToServerTransformTime
  TotalSamples: 13
  Accumulator: 004ms752.575us
  ValueRate: 019ms262.590us / second
  Rate: 66.7312 / second
  Percentiles: 1%=095.363us; 5%=095.363us; 10%=101.134us; 20%=103.317us; 50%=142.475us; 80%=191.082us; 90%=293.646us; 95%=002ms937.578us; 99%=002ms937.578us
Counter: CreateCompileHandles
  Value: 10
Counter: CreateDataHandles
  Value: 49
Counter: CreateXlaTensor
  Value: 140
Counter: DestroyDataHandles
  Value: 36
Counter: DestroyXlaTensor
  Value: 136
Counter: DeviceDataCacheMiss
  Value: 3
Counter: MarkStep
  Value: 10
Counter: ReleaseDataHandles
  Value: 36
Counter: UncachedCompile
  Value: 10
Counter: XRTAllocateFromTensor_Empty
  Value: 2
Counter: XrtCompile_Empty
  Value: 32
Counter: XrtExecuteChained_Empty
  Value: 32
Counter: XrtExecute_Empty
  Value: 32
Counter: XrtRead_Empty
  Value: 32
Counter: XrtReleaseAllocationHandle_Empty
  Value: 32
Counter: XrtReleaseCompileHandle_Empty
  Value: 32
Counter: XrtSessionCount
  Value: 3
Counter: XrtSubTuple_Empty
  Value: 32
Counter: xla::div
  Value: 10
Counter: xla::empty
  Value: 20
Counter: xla::expand
  Value: 10
Counter: xla::fill_
  Value: 10
Counter: xla::mean
  Value: 10
Counter: xla::mul
  Value: 40
Counter: xla::pow
  Value: 20
Counter: xla::uniform_
  Value: 10
Metric: XrtAllocateFromTensor
  TotalSamples: 1079
  Accumulator: 803ms277.675us
  Mean: 742.561us
  StdDev: 537.424us
  Rate: 0.817107 / second
  Percentiles: 25%=486.971us; 50%=649.853us; 80%=001ms012.873us; 90%=001ms171.306us; 95%=001ms257.750us; 99%=003ms355.855us
Metric: XrtCompile
  TotalSamples: 533
  Accumulator: 02m40s854ms759.261us
  Mean: 187ms342.888us
  StdDev: 307ms982.820us
  Rate: 0.423726 / second
  Percentiles: 25%=911.613us; 50%=002ms557.230us; 80%=473ms138.133us; 90%=722ms301.216us; 95%=891ms649.185us; 99%=986ms992.509us
Metric: XrtExecute
  TotalSamples: 822
  Accumulator: 18s137ms744.893us
  Mean: 022ms064.167us
  StdDev: 212ms447.747us
  Rate: 0.655538 / second
  Percentiles: 25%=921.875us; 50%=002ms106.908us; 80%=007ms858.298us; 90%=020ms610.508us; 95%=038ms121.742us; 99%=089ms036.666us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReleaseAllocation
  TotalSamples: 1493
  Accumulator: 026ms136.058us
  Mean: 017.269us
  StdDev: 019.542us
  Rate: 1.37791 / second
  Percentiles: 25%=009.958us; 50%=013.408us; 80%=020.130us; 90%=025.864us; 95%=034.832us; 99%=088.058us

--------------------------------------------------
Metrics for should_reduce=False
Total time:  0.08255600929260254
Time for last iteration:  0.004457712173461914
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 015ms095.063us
  Percentiles: 1%=015ms095.063us; 5%=015ms095.063us; 10%=015ms095.063us; 20%=015ms095.063us; 50%=015ms095.063us; 80%=015ms095.063us; 90%=015ms095.063us; 95%=015ms095.063us; 99%=015ms095.063us
Metric: DeviceLockWait
  TotalSamples: 10
  Accumulator: 021ms895.794us
  ValueRate: 338ms269.304us / second
  Rate: 161.884 / second
  Percentiles: 1%=002.341us; 5%=002.341us; 10%=002.676us; 20%=002.865us; 50%=002ms689.400us; 80%=002ms434.702us; 90%=013ms532.792us; 95%=013ms532.792us; 99%=013ms532.792us
Metric: ExecuteTime
  TotalSamples: 9
  Accumulator: 041ms052.465us
  ValueRate: 997ms474.585us / second
  Rate: 218.678 / second
  Percentiles: 1%=002ms532.743us; 5%=002ms532.743us; 10%=002ms532.743us; 20%=002ms651.301us; 50%=004ms121.501us; 80%=005ms933.482us; 90%=016ms690.854us; 95%=016ms690.854us; 99%=016ms690.854us
Metric: InputOutputAliasCount
  TotalSamples: 1
  Accumulator: 4.00
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=4.00; 80%=4.00; 90%=4.00; 95%=4.00; 99%=4.00
Metric: OutboundData
  TotalSamples: 13
  Accumulator: 92.00B
  ValueRate: 1.21KB / second
  Rate: 175.355 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: ReleaseDataHandlesTime
  TotalSamples: 14
  Accumulator: 053ms663.961us
  ValueRate: 01s485ms659.345us / second
  Rate: 394.677 / second
  Percentiles: 1%=479.256us; 5%=479.256us; 10%=569.707us; 20%=600.137us; 50%=003ms193.790us; 80%=006ms810.828us; 90%=013ms861.852us; 95%=015ms037.775us; 99%=015ms037.775us
Metric: TensorsGraphSize
  TotalSamples: 10
  Accumulator: 280.00
  ValueRate: 6070.05 / second
  Rate: 216.788 / second
  Percentiles: 1%=28.00; 5%=28.00; 10%=28.00; 20%=28.00; 50%=28.00; 80%=28.00; 90%=28.00; 95%=28.00; 99%=28.00
Metric: TransferToServerTime
  TotalSamples: 13
  Accumulator: 032ms789.639us
  ValueRate: 459ms685.554us / second
  Rate: 187.574 / second
  Percentiles: 1%=001ms394.765us; 5%=001ms394.765us; 10%=001ms404.075us; 20%=001ms476.780us; 50%=002ms616.511us; 80%=002ms288.200us; 90%=004ms123.058us; 95%=009ms766.136us; 99%=009ms766.136us
Metric: TransferToServerTransformTime
  TotalSamples: 13
  Accumulator: 005ms026.329us
  ValueRate: 068ms788.507us / second
  Rate: 175.327 / second
  Percentiles: 1%=146.277us; 5%=146.277us; 10%=147.701us; 20%=155.975us; 50%=180.684us; 80%=253.012us; 90%=310.828us; 95%=003ms698.624us; 99%=003ms698.624us
Counter: CachedCompile
  Value: 9
Counter: CreateCompileHandles
  Value: 1
Counter: CreateDataHandles
  Value: 49
Counter: CreateXlaTensor
  Value: 130
Counter: DestroyDataHandles
  Value: 40
Counter: DestroyXlaTensor
  Value: 126
Counter: DeviceDataCacheMiss
  Value: 3
Counter: MarkStep
  Value: 10
Counter: ReleaseDataHandles
  Value: 45
Counter: UncachedCompile
  Value: 1
Counter: XRTAllocateFromTensor_Empty
  Value: 2
Counter: XrtCompile_Empty
  Value: 64
Counter: XrtExecuteChained_Empty
  Value: 64
Counter: XrtExecute_Empty
  Value: 64
Counter: XrtRead_Empty
  Value: 64
Counter: XrtReleaseAllocationHandle_Empty
  Value: 64
Counter: XrtReleaseCompileHandle_Empty
  Value: 64
Counter: XrtSessionCount
  Value: 5
Counter: XrtSubTuple_Empty
  Value: 64
Counter: xla::div
  Value: 10
Counter: xla::empty
  Value: 20
Counter: xla::expand
  Value: 10
Counter: xla::fill_
  Value: 10
Counter: xla::mean
  Value: 10
Counter: xla::mul
  Value: 40
Counter: xla::pow
  Value: 20
Counter: xla::uniform_
  Value: 10
Metric: XrtAllocateFromTensor
  TotalSamples: 1174
  Accumulator: 853ms317.391us
  Mean: 709.180us
  StdDev: 497.063us
  Rate: 0.864416 / second
  Percentiles: 25%=487.351us; 50%=620.014us; 80%=958.856us; 90%=001ms141.296us; 95%=001ms242.618us; 99%=002ms900.027us
Metric: XrtCompile
  TotalSamples: 541
  Accumulator: 02m40s856ms232.047us
  Mean: 185ms577.139us
  StdDev: 306ms539.762us
  Rate: 0.426521 / second
  Percentiles: 25%=884.438us; 50%=002ms546.978us; 80%=472ms491.039us; 90%=722ms197.049us; 95%=891ms547.607us; 99%=986ms992.509us
Metric: XrtExecute
  TotalSamples: 889
  Accumulator: 18s217ms985.027us
  Mean: 020ms491.547us
  StdDev: 204ms359.693us
  Rate: 0.703044 / second
  Percentiles: 25%=900.511us; 50%=002ms930.189us; 80%=006ms345.436us; 90%=019ms203.348us; 95%=038ms720.872us; 99%=089ms036.666us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReleaseAllocation
  TotalSamples: 1624
  Accumulator: 029ms992.014us
  Mean: 017.682us
  StdDev: 018.332us
  Rate: 1.35896 / second
  Percentiles: 25%=010.122us; 50%=014.043us; 80%=021.058us; 90%=027.199us; 95%=036.781us; 99%=082.044us

--------------------------------------------------
```

1. Run above script

## Expected behavior

I'd expect this to run without re-compiling each step.

## Environment

 - Reproducible on XLA backend [CPU/TPU]: TPU
 - torch_xla version: nightly (I'm using torch_xla-1.6+88d6189)

**Comment by dlibenzi** [comment]
Wonder if you could run using `debug_run.py` and post the tar.gz:

https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information

**Comment by matt-peters** [comment]
Attached it here. Thanks for taking a look!

[debug_run.tar.gz](https://github.com/pytorch/xla/files/4886481/debug_run.tar.gz)

**Comment by dlibenzi** [comment]
From that debug run data, everything looks fine to me:
```
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 124ms379.472us
  Percentiles: 1%=124ms379.472us; 5%=124ms379.472us; 10%=124ms379.472us; 20%=124ms379.472us; 50%=124ms379.472us; 80%=124ms379.472us; 90%=124ms379.472us; 95%=124ms379.472us; 99%=124ms379.472us

Metric: ExecuteTime
  TotalSamples: 10
  Accumulator: 032ms682.995us
  ValueRate: 222ms348.073us / second
  Rate: 70.179 / second
  Percentiles: 1%=002ms504.334us; 5%=002ms504.334us; 10%=002ms527.337us; 20%=002ms695.047us; 50%=002ms460.731us; 80%=005ms102.316us; 90%=008ms778.086us; 95%=008ms778.086us; 99%=008ms778.086us


```


1 Compile, 10 Executions.

**Comment by matt-peters** [comment]
There are two separate spawn calls in the script I posted above. This is the metrics from the second that doesn't do the all reduce in the backward pass (with `should_reduce=False`) to show that the problem is specifically isolated to that call.  The metrics report from both is pasted into my original comment, see the very top of the log:

```
Metrics for should_reduce=True
Total time:  0.21088099479675293
Time for last iteration:  0.013144254684448242
Metric: CompileTime
  TotalSamples: 10
  Accumulator: 067ms885.816us
  ValueRate: 377ms161.815us / second
  Rate: 56.3889 / second
  Percentiles: 1%=003ms808.219us; 5%=003ms808.219us; 10%=003ms898.512us; 20%=003ms367.656us; 50%=005ms320.894us; 80%=015ms588.378us; 90%=018ms930.982us; 95%=018ms930.982us; 99%=018ms930.982us
```

**Comment by matt-peters** [comment]
Here is a debug_run.tar.gz that just does the all_reduce in backward pass (it omits the `run_benchmark(False)` call in the script above)

[debug_run.tar.gz](https://github.com/pytorch/xla/files/4886675/debug_run.tar.gz)

**Comment by dlibenzi** [comment]
Graph keeps growing as you need to zero the grads after each step, otherwise they add to themselves.
This is why the `optimizer.zero_grad()` calls are there.

**Comment by matt-peters** [comment]
I'm not sure I understand.  Is this a consequence of the multiple backward calls without calling zero_grad?  Why doesn't the version without the all_reduce re-compile then?

**Comment by dlibenzi** [comment]
OK, I see we have an issue here.
The `xm.all_reduce()` get called from autograd threads, which have not the correct information (which is stored in main threads TLS.

**Comment by dlibenzi** [comment]
WIP https://github.com/pytorch/xla/pull/2325

**Comment by dlibenzi** [comment]
Can you try with tomorrow nightly builds if this is solved?

**Comment by matt-peters** [comment]
Will do. Thanks for the super quick fix!

**Comment by dlibenzi** [comment]
Looks fixed in my test:
```
Metrics for should_reduce=True
Total time:  0.16447710990905762
Time for last iteration:  0.0055675506591796875
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 016ms493.808us
  Percentiles: 1%=016ms493.808us; 5%=016ms493.808us; 10%=016ms493.808us; 20%=016ms493.808us; 50%=016ms493.808us; 80%=016ms493.808us; 90%=016ms493.808us; 95%=016ms493.808us; 99%=016ms493.808us
Metric: DeviceLockWait
  TotalSamples: 10
  Accumulator: 100ms940.344us
  ValueRate: 677ms796.933us / second
  Rate: 67.7201 / second
  Percentiles: 1%=002.249us; 5%=002.249us; 10%=002.342us; 20%=002.626us; 50%=004ms390.501us; 80%=022ms563.832us; 90%=040ms091.167us; 95%=040ms091.167us; 99%=040ms091.167us
Metric: ExecuteTime
  TotalSamples: 9
  Accumulator: 126ms124.067us
  ValueRate: 01s189ms848.925us / second
  Rate: 84.8342 / second
  Percentiles: 1%=002ms956.113us; 5%=002ms956.113us; 10%=002ms956.113us; 20%=002ms370.720us; 50%=007ms636.548us; 80%=024ms676.582us; 90%=043ms531.452us; 95%=043ms531.452us; 99%=043ms531.452us
Metric: InputOutputAliasCount
  TotalSamples: 1
  Accumulator: 4.00
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=4.00; 80%=4.00; 90%=4.00; 95%=4.00; 99%=4.00
Metric: OutboundData
  TotalSamples: 13
  Accumulator: 92.00B
  ValueRate: 588.73B / second
  Rate: 83.1907 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: ReleaseDataHandlesTime
  TotalSamples: 16
  Accumulator: 090ms245.859us
  ValueRate: 882ms228.629us / second
  Rate: 156.413 / second
  Percentiles: 1%=492.052us; 5%=492.052us; 10%=542.443us; 20%=556.708us; 50%=004ms078.740us; 80%=008ms446.736us; 90%=018ms437.275us; 95%=027ms096.216us; 99%=027ms096.216us
Metric: TensorsGraphSize
  TotalSamples: 10
  Accumulator: 300.00
  ValueRate: 2297.33 / second
  Rate: 76.5776 / second
  Percentiles: 1%=30.00; 5%=30.00; 10%=30.00; 20%=30.00; 50%=30.00; 80%=30.00; 90%=30.00; 95%=30.00; 99%=30.00
Metric: TransferToServerTime
  TotalSamples: 13
  Accumulator: 036ms352.111us
  ValueRate: 234ms359.150us / second
  Rate: 83.81 / second
  Percentiles: 1%=971.129us; 5%=971.129us; 10%=001ms239.987us; 20%=001ms413.780us; 50%=002ms815.482us; 80%=005ms688.383us; 90%=006ms971.834us; 95%=007ms485.620us; 99%=007ms485.620us
Metric: TransferToServerTransformTime
  TotalSamples: 13
  Accumulator: 004ms661.021us
  ValueRate: 023ms425.054us / second
  Rate: 83.1805 / second
  Percentiles: 1%=110.275us; 5%=110.275us; 10%=120.218us; 20%=124.686us; 50%=144.570us; 80%=194.784us; 90%=301.228us; 95%=002ms791.962us; 99%=002ms791.962us
Counter: CachedCompile
  Value: 9
Counter: CreateCompileHandles
  Value: 1
Counter: CreateDataHandles
  Value: 49
Counter: CreateXlaTensor
  Value: 140
Counter: DestroyDataHandles
  Value: 45
Counter: DestroyXlaTensor
  Value: 136
Counter: DeviceDataCacheMiss
  Value: 3
Counter: MarkStep
  Value: 10
Counter: ReleaseDataHandles
  Value: 45
Counter: UncachedCompile
  Value: 1
Counter: XRTAllocateFromTensor_Empty
  Value: 2
Counter: XrtCompile_Empty
  Value: 80
Counter: XrtExecuteChained_Empty
  Value: 80
Counter: XrtExecute_Empty
  Value: 80
Counter: XrtMemoryInfo_Empty
  Value: 80
Counter: XrtRead_Empty
  Value: 80
Counter: XrtReleaseAllocationHandle_Empty
  Value: 80
Counter: XrtReleaseCompileHandle_Empty
  Value: 80
Counter: XrtSessionCount
  Value: 6
Counter: XrtSubTuple_Empty
  Value: 80
Counter: xla::div
  Value: 10
Counter: xla::empty
  Value: 20
Counter: xla::expand
  Value: 10
Counter: xla::fill_
  Value: 10
Counter: xla::mean
  Value: 10
Counter: xla::mul
  Value: 40
Counter: xla::pow
  Value: 20
Counter: xla::uniform_
  Value: 10
Metric: XrtAllocateFromTensor
  TotalSamples: 40197
  Accumulator: 20s975ms816.002us
  Mean: 607.944us
  StdDev: 710.134us
  Rate: 0.010452 / second
  Percentiles: 25%=276.063us; 50%=435.268us; 80%=717.867us; 90%=993.582us; 95%=002ms731.840us; 99%=004ms005.712us
Metric: XrtCompile
  TotalSamples: 42516
  Accumulator: 57m15s990ms823.577us
  Mean: 004ms671.159us
  StdDev: 022ms586.416us
  Rate: 0.0104524 / second
  Percentiles: 25%=166.289us; 50%=498.180us; 80%=002ms772.063us; 90%=003ms373.889us; 95%=004ms463.359us; 99%=122ms750.875us
Metric: XrtExecute
  TotalSamples: 86135
  Accumulator: 09m54s336ms978.012us
  Mean: 057ms156.459us
  StdDev: 345ms472.875us
  Rate: 0.0104466 / second
  Percentiles: 25%=001ms053.253us; 50%=001ms442.465us; 80%=024ms785.085us; 90%=059ms898.494us; 95%=082ms881.768us; 99%=01s296ms328.902us
Metric: XrtExecuteChained
  TotalSamples: 1836
  Accumulator: 36m53s102ms205.687us
  Mean: 01s403ms003.227us
  StdDev: 02s027ms546.179us
  Rate: 0.0135235 / second
  Percentiles: 25%=007ms518.337us; 50%=021ms199.814us; 80%=04s043ms592.067us; 90%=05s740ms165.877us; 95%=05s771ms641.828us; 99%=05s814ms415.537us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 99130
  Accumulator: 49s039ms056.798us
  Mean: 618.900us
  StdDev: 003ms510.057us
  Rate: 4.38329 / second
  Percentiles: 25%=334.727us; 50%=418.959us; 80%=514.795us; 90%=609.790us; 95%=686.978us; 99%=002ms675.424us
Metric: XrtReleaseAllocation
  TotalSamples: 101673
  Accumulator: 05s931ms087.022us
  Mean: 216.091us
  StdDev: 348.978us
  Rate: 0.0104562 / second
  Percentiles: 25%=020.030us; 50%=036.471us; 80%=355.265us; 90%=737.847us; 95%=001ms050.706us; 99%=002ms595.852us
Metric: XrtReleaseCompilation
  TotalSamples: 21825
  Accumulator: 084ms821.136us
  Mean: 004.351us
  StdDev: 010.508us
  Rate: 4.98061 / second
  Percentiles: 25%=002.618us; 50%=003.240us; 80%=003.786us; 90%=004.708us; 95%=007.543us; 99%=027.365us

--------------------------------------------------
Metrics for should_reduce=False
Total time:  0.14017534255981445
Time for last iteration:  0.005582094192504883
Metric: CompileTime
  TotalSamples: 1
  Accumulator: 018ms029.585us
  Percentiles: 1%=018ms029.585us; 5%=018ms029.585us; 10%=018ms029.585us; 20%=018ms029.585us; 50%=018ms029.585us; 80%=018ms029.585us; 90%=018ms029.585us; 95%=018ms029.585us; 99%=018ms029.585us
Metric: DeviceLockWait
  TotalSamples: 10
  Accumulator: 082ms794.935us
  ValueRate: 667ms416.164us / second
  Rate: 81.5963 / second
  Percentiles: 1%=002.529us; 5%=002.529us; 10%=002.918us; 20%=002.969us; 50%=003ms922.721us; 80%=015ms693.871us; 90%=051ms449.501us; 95%=051ms449.501us; 99%=051ms449.501us
Metric: ExecuteTime
  TotalSamples: 10
  Accumulator: 103ms260.355us
  ValueRate: 01s018ms267.625us / second
  Rate: 98.6117 / second
  Percentiles: 1%=002ms626.535us; 5%=002ms626.535us; 10%=002ms650.240us; 20%=002ms424.716us; 50%=005ms248.389us; 80%=017ms427.722us; 90%=054ms637.250us; 95%=054ms637.250us; 99%=054ms637.250us
Metric: InputOutputAliasCount
  TotalSamples: 1
  Accumulator: 4.00
  Percentiles: 1%=4.00; 5%=4.00; 10%=4.00; 20%=4.00; 50%=4.00; 80%=4.00; 90%=4.00; 95%=4.00; 99%=4.00
Metric: OutboundData
  TotalSamples: 13
  Accumulator: 92.00B
  ValueRate: 699.44B / second
  Rate: 98.8339 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=4.00B; 50%=8.00B; 80%=8.00B; 90%=8.00B; 95%=8.00B; 99%=8.00B
Metric: ReleaseDataHandlesTime
  TotalSamples: 16
  Accumulator: 146ms770.658us
  ValueRate: 01s497ms338.725us / second
  Rate: 164.35 / second
  Percentiles: 1%=439.825us; 5%=439.825us; 10%=497.874us; 20%=592.945us; 50%=005ms937.556us; 80%=011ms535.148us; 90%=022ms402.860us; 95%=051ms330.494us; 99%=051ms330.494us
Metric: TensorsGraphSize
  TotalSamples: 10
  Accumulator: 280.00
  ValueRate: 2692.21 / second
  Rate: 96.1504 / second
  Percentiles: 1%=28.00; 5%=28.00; 10%=28.00; 20%=28.00; 50%=28.00; 80%=28.00; 90%=28.00; 95%=28.00; 99%=28.00
Metric: TransferToServerTime
  TotalSamples: 13
  Accumulator: 030ms738.770us
  ValueRate: 234ms472.229us / second
  Rate: 102.497 / second
  Percentiles: 1%=001ms308.658us; 5%=001ms308.658us; 10%=001ms339.049us; 20%=001ms390.482us; 50%=002ms576.823us; 80%=002ms387.485us; 90%=004ms549.714us; 95%=008ms151.054us; 99%=008ms151.054us
Metric: TransferToServerTransformTime
  TotalSamples: 13
  Accumulator: 004ms208.073us
  ValueRate: 032ms988.218us / second
  Rate: 98.8212 / second
  Percentiles: 1%=103.192us; 5%=103.192us; 10%=123.310us; 20%=126.139us; 50%=150.789us; 80%=229.082us; 90%=256.318us; 95%=002ms250.484us; 99%=002ms250.484us
Counter: CachedCompile
  Value: 9
Counter: CreateCompileHandles
  Value: 1
Counter: CreateDataHandles
  Value: 53
Counter: CreateXlaTensor
  Value: 130
Counter: DestroyDataHandles
  Value: 46
Counter: DestroyXlaTensor
  Value: 126
Counter: DeviceDataCacheMiss
  Value: 3
Counter: MarkStep
  Value: 10
Counter: ReleaseDataHandles
  Value: 46
Counter: UncachedCompile
  Value: 1
Counter: XRTAllocateFromTensor_Empty
  Value: 2
Counter: XrtCompile_Empty
  Value: 96
Counter: XrtExecuteChained_Empty
  Value: 96
Counter: XrtExecute_Empty
  Value: 96
Counter: XrtMemoryInfo_Empty
  Value: 96
Counter: XrtRead_Empty
  Value: 96
Counter: XrtReleaseAllocationHandle_Empty
  Value: 96
Counter: XrtReleaseCompileHandle_Empty
  Value: 96
Counter: XrtSessionCount
  Value: 7
Counter: XrtSubTuple_Empty
  Value: 96
Counter: xla::div
  Value: 10
Counter: xla::empty
  Value: 20
Counter: xla::expand
  Value: 10
Counter: xla::fill_
  Value: 10
Counter: xla::mean
  Value: 10
Counter: xla::mul
  Value: 40
Counter: xla::pow
  Value: 20
Counter: xla::uniform_
  Value: 10
Metric: XrtAllocateFromTensor
  TotalSamples: 40301
  Accumulator: 20s040ms124.723us
  Mean: 620.251us
  StdDev: 677.258us
  Rate: 0.0104508 / second
  Percentiles: 25%=296.654us; 50%=486.213us; 80%=743.272us; 90%=975.741us; 95%=002ms662.779us; 99%=004ms654.539us
Metric: XrtCompile
  TotalSamples: 42524
  Accumulator: 57m15s993ms985.907us
  Mean: 004ms649.461us
  StdDev: 022ms588.228us
  Rate: 0.0104511 / second
  Percentiles: 25%=166.289us; 50%=489.073us; 80%=002ms705.397us; 90%=003ms260.119us; 95%=004ms463.359us; 99%=122ms750.875us
Metric: XrtExecute
  TotalSamples: 86223
  Accumulator: 09m54s449ms951.118us
  Mean: 057ms181.431us
  StdDev: 345ms468.934us
  Rate: 0.0104454 / second
  Percentiles: 25%=001ms057.839us; 50%=001ms460.859us; 80%=024ms785.085us; 90%=059ms898.494us; 95%=082ms881.768us; 99%=01s296ms328.902us
Metric: XrtExecuteChained
  TotalSamples: 1836
  Accumulator: 36m53s102ms205.687us
  Mean: 01s403ms003.227us
  StdDev: 02s027ms546.179us
  Rate: 0.0135235 / second
  Percentiles: 25%=007ms518.337us; 50%=021ms199.814us; 80%=04s043ms592.067us; 90%=05s740ms165.877us; 95%=05s771ms641.828us; 99%=05s814ms415.537us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 99130
  Accumulator: 49s039ms056.798us
  Mean: 618.900us
  StdDev: 003ms510.057us
  Rate: 4.38329 / second
  Percentiles: 25%=334.727us; 50%=418.959us; 80%=514.795us; 90%=609.790us; 95%=686.978us; 99%=002ms675.424us
Metric: XrtReleaseAllocation
  TotalSamples: 101820
  Accumulator: 05s935ms846.626us
  Mean: 165.288us
  StdDev: 312.387us
  Rate: 0.0104568 / second
  Percentiles: 25%=017.337us; 50%=029.434us; 80%=220.863us; 90%=584.789us; 95%=894.623us; 99%=001ms484.967us
Metric: XrtReleaseCompilation
  TotalSamples: 21825
  Accumulator: 084ms821.136us
  Mean: 004.351us
  StdDev: 010.508us
  Rate: 4.98061 / second
  Percentiles: 25%=002.618us; 50%=003.240us; 80%=003.786us; 90%=004.708us; 95%=007.543us; 99%=027.365us

--------------------------------------------------
```
