### ISSUE TITLE
Lowering repeat_interleave.

### ISSUE THREAD

**Issue by sharvil** [pytorch/xla#2400]
## 🚀 Feature
Please add support for `repeat_interleave`.

## Motivation

I'm training a model with fixed upsampling using `repeat_interleave` and found that this operation is not lowered by PyTorch/XLA. See attached metrics report after 30 iterations of the training loop.

```
Metric: CompileTime
  TotalSamples: 38
  Accumulator: 01m03s896ms487.041us
  ValueRate: 947ms721.139us / second
  Rate: 0.571978 / second
  Percentiles: 1%=823.808us; 5%=951.718us; 10%=001ms109.568us; 20%=002ms663.037us; 50%=006ms112.510us; 80%=02s729ms377.641us; 90%=02s829ms146.757us; 95%=23s601ms299.758us; 99%=29s355ms308.307us
Metric: DeviceLockWait
  TotalSamples: 690
  Accumulator: 002ms595.553us
  ValueRate: 010.020us / second
  Rate: 4.33318 / second
  Percentiles: 1%=000.910us; 5%=000.979us; 10%=001.020us; 20%=001.080us; 50%=001.331us; 80%=002.330us; 90%=002.940us; 95%=003.499us; 99%=027.600us
Metric: ExecuteTime
  TotalSamples: 602
  Accumulator: 09s199ms470.805us
  ValueRate: 058ms422.296us / second
  Rate: 3.82307 / second
  Percentiles: 1%=001ms380.698us; 5%=001ms459.317us; 10%=002ms509.019us; 20%=002ms589.257us; 50%=002ms949.507us; 80%=008ms783.829us; 90%=018ms824.271us; 95%=025ms624.689us; 99%=246ms658.101us
Metric: InboundData
  TotalSamples: 11998
  Accumulator: 3.40GB
  ValueRate: 34.47MB / second
  Rate: 149.682 / second
  Percentiles: 1%=8.00B; 5%=256.00B; 10%=256.00B; 20%=256.00B; 50%=4.00KB; 80%=32.00KB; 90%=64.00KB; 95%=96.00KB; 99%=12.00MB
Metric: InputOutputAliasCount
  TotalSamples: 8
  Accumulator: 3172.00
  ValueRate: 81.94 / second
  Rate: 0.206669 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=1.00; 80%=1582.00; 90%=1584.00; 95%=1584.00; 99%=1584.00
Metric: IrValueTensorToXlaData
  TotalSamples: 542
  Accumulator: 02s391ms576.792us
  ValueRate: 015ms827.861us / second
  Rate: 3.36182 / second
  Percentiles: 1%=001ms034.318us; 5%=001ms102.018us; 10%=001ms192.937us; 20%=001ms300.559us; 50%=002ms607.407us; 80%=003ms526.907us; 90%=005ms860.753us; 95%=007ms456.277us; 99%=130ms383.014us
Metric: OutboundData
  TotalSamples: 617
  Accumulator: 124.82MB
  ValueRate: 792.78KB / second
  Rate: 3.82692 / second
  Percentiles: 1%=4.00B; 5%=4.00B; 10%=4.00B; 20%=256.00B; 50%=4.00KB; 80%=64.00KB; 90%=96.00KB; 95%=192.00KB; 99%=12.00MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 5888
  Accumulator: 05s294ms560.254us
  ValueRate: 051ms043.483us / second
  Rate: 52.5459 / second
  Percentiles: 1%=475.930us; 5%=517.390us; 10%=550.589us; 20%=593.138us; 50%=729.649us; 80%=001ms013.519us; 90%=001ms340.929us; 95%=002ms917.029us; 99%=006ms558.444us
Metric: TensorsGraphSize
  TotalSamples: 602
  Accumulator: 508648.00
  ValueRate: 3229.97 / second
  Rate: 3.82276 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=1.00; 80%=7.00; 90%=313.00; 95%=541.00; 99%=15934.00
Metric: TransferFromServerTime
  TotalSamples: 11998
  Accumulator: 45s978ms396.513us
  ValueRate: 464ms116.128us / second
  Rate: 149.682 / second
  Percentiles: 1%=919.868us; 5%=001ms004.639us; 10%=001ms085.749us; 20%=001ms181.949us; 50%=001ms473.339us; 80%=002ms967.979us; 90%=002ms479.628us; 95%=004ms205.756us; 99%=059ms698.980us
Metric: TransferToServerTime
  TotalSamples: 617
  Accumulator: 03s561ms551.127us
  ValueRate: 016ms882.147us / second
  Rate: 3.82702 / second
  Percentiles: 1%=001ms029.518us; 5%=001ms099.258us; 10%=001ms192.098us; 20%=001ms315.808us; 50%=002ms666.667us; 80%=003ms515.148us; 90%=005ms831.314us; 95%=007ms220.182us; 99%=130ms088.085us
Metric: TransferToServerTransformTime
  TotalSamples: 617
  Accumulator: 200ms295.294us
  ValueRate: 001ms242.325us / second
  Rate: 3.82692 / second
  Percentiles: 1%=044.219us; 5%=061.619us; 10%=085.410us; 20%=130.340us; 50%=191.180us; 80%=256.509us; 90%=457.349us; 95%=951.498us; 99%=004ms669.613us
Counter: CachedCompile
  Value: 564
Counter: CreateCompileHandles
  Value: 38
Counter: CreateDataHandles
  Value: 48651
Counter: CreateXlaTensor
  Value: 154563
Counter: DestroyDataHandles
  Value: 46991
Counter: DestroyXlaTensor
  Value: 152980
Counter: DeviceDataCacheMiss
  Value: 75
Counter: MarkStep
  Value: 30
Counter: ReleaseDataHandles
  Value: 46991
Counter: UncachedCompile
  Value: 38
Counter: XRTAllocateFromTensor_Empty
  Value: 35
Counter: XrtCompile_Empty
  Value: 144
Counter: XrtExecuteChained_Empty
  Value: 144
Counter: XrtExecute_Empty
  Value: 144
Counter: XrtMemoryInfo_Empty
  Value: 144
Counter: XrtRead_Empty
  Value: 144
Counter: XrtReleaseAllocationHandle_Empty
  Value: 144
Counter: XrtReleaseCompileHandle_Empty
  Value: 144
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 144
Counter: aten::_local_scalar_dense
  Value: 148
Counter: aten::isnan
  Value: 30
Counter: aten::repeat_interleave
  Value: 30
Counter: xla::_index_put_impl_
  Value: 30
Counter: xla::_log_softmax
  Value: 30
Counter: xla::_log_softmax_backward_data
  Value: 30
Counter: xla::_s_where
  Value: 30
Counter: xla::add
  Value: 5580
Counter: xla::add_
  Value: 36391
Counter: xla::addcdiv_
  Value: 11670
Counter: xla::addcmul_
  Value: 11670
Counter: xla::any
  Value: 30
Counter: xla::argmin
  Value: 30
Counter: xla::as_strided
  Value: 512
Counter: xla::cat
  Value: 1200
Counter: xla::clone
  Value: 421
Counter: xla::convolution_backward_overrideable
  Value: 5820
Counter: xla::convolution_overrideable
  Value: 5850
Counter: xla::copy_
  Value: 12452
Counter: xla::div
  Value: 11760
Counter: xla::empty
  Value: 2730
Counter: xla::empty_strided
  Value: 512
Counter: xla::expand
  Value: 240
Counter: xla::fill_
  Value: 30
Counter: xla::index
  Value: 60
Counter: xla::index_add_
  Value: 30
Counter: xla::index_put_
  Value: 30
Counter: xla::index_select
  Value: 30
Counter: xla::lt
  Value: 30
Counter: xla::max
  Value: 30
Counter: xla::mean
  Value: 60
Counter: xla::min
  Value: 30
Counter: xla::mul
  Value: 3240
Counter: xla::mul_
  Value: 23340
Counter: xla::neg
  Value: 30
Counter: xla::nll_loss_backward
  Value: 30
Counter: xla::nll_loss_forward
  Value: 30
Counter: xla::permute
  Value: 150
Counter: xla::pow
  Value: 150
Counter: xla::relu
  Value: 780
Counter: xla::scatter_
  Value: 30
Counter: xla::sigmoid
  Value: 600
Counter: xla::sigmoid_backward
  Value: 600
Counter: xla::slice
  Value: 2640
Counter: xla::sqrt
  Value: 11670
Counter: xla::squeeze
  Value: 16230
Counter: xla::sub
  Value: 150
Counter: xla::sum
  Value: 1350
Counter: xla::tanh
  Value: 600
Counter: xla::tanh_backward
  Value: 600
Counter: xla::threshold_backward
  Value: 780
Counter: xla::unsqueeze
  Value: 18930
Counter: xla::view
  Value: 150
Counter: xla::zero_
  Value: 13439
Metric: XrtAllocateFromTensor
  TotalSamples: 4945
  Accumulator: 03s213ms465.280us
  Mean: 638.182us
  StdDev: 240.662us
  Rate: 17.7942 / second
  Percentiles: 25%=469.637us; 50%=628.255us; 80%=818.694us; 90%=912.252us; 95%=001ms025.788us; 99%=001ms362.507us
Metric: XrtCompile
  TotalSamples: 304
  Accumulator: 06m08s978ms840.760us
  Mean: 01s210ms453.424us
  StdDev: 05s947ms326.360us
  Rate: 4.57455 / second
  Percentiles: 25%=135.732us; 50%=002ms417.198us; 80%=011ms285.542us; 90%=02s805ms189.901us; 95%=08s161ms443.459us; 99%=29s881ms164.635us
Metric: XrtExecute
  TotalSamples: 4817
  Accumulator: 01m06s989ms137.120us
  Mean: 037ms847.714us
  StdDev: 080ms834.778us
  Rate: 17.794 / second
  Percentiles: 25%=001ms234.960us; 50%=007ms101.157us; 80%=017ms299.367us; 90%=189ms244.357us; 95%=225ms991.681us; 99%=317ms033.310us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 95987
  Accumulator: 01m03s882ms715.907us
  Mean: 333.879us
  StdDev: 097.098us
  Rate: 3328.86 / second
  Percentiles: 25%=263.115us; 50%=306.327us; 80%=402.194us; 90%=467.695us; 95%=524.542us; 99%=691.244us
Metric: XrtReleaseAllocation
  TotalSamples: 48202
  Accumulator: 01s337ms442.257us
  Mean: 033.677us
  StdDev: 089.249us
  Rate: 332.318 / second
  Percentiles: 25%=007.565us; 50%=011.404us; 80%=031.388us; 90%=065.211us; 95%=110.325us; 99%=447.428us
```
