### ISSUE TITLE
Custom Pretraining script for Electra (NLP) very slow on TPU compare to TF

### ISSUE THREAD

**Issue by Shiro-LK** [pytorch/xla#2530]
## ❓ Questions and Help

Hi,

I am currently trying to code an electra pretraining script for tpu. I experimented it first on GPU, and it seems to work well, the computing time is similar to the official repo on TF. Unfortunately, with TPU it is quite slow.
for instance for 300 steps, it is taking around 9/10 minutes so roughtly 1 steps per seconds with TPU v2-8 and a batch size of 128x8.
On TF, 1 Million steps take roughtly 10 hours, so 300 steps should be less than 1 minutes. I would like to find where the issue comes from ? is there some tools to measure the computing time for multiprocessing ? I am using the transformer library for the Electra Model (huggingface)

some example of my training loop : 
 ```
        ids, targets, attention_mask, token_types, _ = batch
        # move to device
        ids = ids.to(device, dtype=torch.long)
        targets = targets.to(device, dtype=torch.long)
        attention_mask = attention_mask.to(device, dtype=torch.long)
        token_types = token_types.to(device, dtype=torch.long)

        # -- Train Generator -- #
        if type(optimizer) == list:
          for opt in optimizer:
            opt.zero_grad()
        else:
          optimizer.zero_grad()
        
        outputs = model(input_ids=ids, attention_mask=attention_mask, token_type_ids= token_types ,masked_lm_labels=targets)
        loss, scores = outputs[:2]
        loss.backward()

        if type(optimizer) == list:
          for opt in optimizer:
            xm.optimizer_step(opt)
        else:
          xm.optimizer_step(optimizer)

        #total_loss += loss.item()

        # -- Compute discriminator inputs -- #

        with torch.no_grad():
            proba_scores = scores# F.softmax(scores, dim=-1)#.float() # 
            predict_words_proba_max, predict_words = torch.max(proba_scores, dim=-1)
            

        

        masks = (targets != -100).long() # 1 if words generated, 0 otherwise
        predictions = predict_words * masks # isolate prediction generate, 0 otherwise
        targets_discriminator = ((predictions != targets)*masks).float() # 1 if replace tokens, 0 otherwise
        inputs_discriminator = predictions + (ids * (~(masks.bool())).long()) 



        # -- Train discriminator -- #

        if type(optimizer_discr) == list:
          #print("zero grad")
          for opt in optimizer_discr:
            opt.zero_grad()
        else:
          optimizer_discr.zero_grad()

        outputs2 = model_discr(input_ids=inputs_discriminator , attention_mask=attention_mask, token_type_ids= token_types) # labels=targets_discriminator, 
        loss2 = loss_disc(targets_discriminator, outputs2[0], device, loss_fct, attention_mask=attention_mask) * 50.0
        
        loss2.backward()
        #total_loss2 += loss2.item()
        
        if type(optimizer_discr) == list:
          for opt in optimizer_discr:
            xm.optimizer_step(opt)
        else:
          xm.optimizer_step(optimizer_discr)

        # update scheduler for Generator and Discriminator
        if scheduler is not None:
            if type(scheduler) == list:
              for schedul in scheduler:
                schedul.step()
            else:
              scheduler.step()


        t.update(1)
        t.refresh()
        
```

**Comment by taylanbil** [comment]
It seems you're sending tensors to device in every step. We strongly suggest to use our Parallel Loaders, which send data to device in the background, and thus overlap model execution, optimizing performance. See [example](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L231)

If the slowness persists when using `MpDeviceLoader`, next step would be to look at the metrics report as in [example](https://github.com/pytorch/xla/blob/master/test/test_train_mp_imagenet.py#L248) after a few steps.

**Comment by Shiro-LK** [comment]
Thank for you reply.
I was using pl.ParallelLoader, which is used by MpDeviceLoader, I change by MpDeviceLoader but I haven't see any difference of speed.

I displayed the metrics function you pointed , is there something wrong in the results ? 

```
###### -- REPORT -- ######
Metric: CompileTime
  TotalSamples: 3
  Accumulator: 01s025ms777.409us
  ValueRate: 085ms092.064us / second
  Rate: 0.249104 / second
  Percentiles: 1%=040ms482.387us; 5%=040ms482.387us; 10%=040ms482.387us; 20%=040ms482.387us; 50%=441ms192.919us; 80%=543ms102.103us; 90%=543ms102.103us; 95%=543ms102.103us; 99%=543ms102.103us
Metric: DeviceLockWait
  TotalSamples: 39
  Accumulator: 230.060us
  ValueRate: 006.194us / second
  Rate: 1.04994 / second
  Percentiles: 1%=003.491us; 5%=004.585us; 10%=004.612us; 20%=004.805us; 50%=005.442us; 80%=006.785us; 90%=008.034us; 95%=008.730us; 99%=013.613us
Metric: ExecuteTime
  TotalSamples: 39
  Accumulator: 21s346ms074.983us
  ValueRate: 570ms335.380us / second
  Rate: 1.04202 / second
  Percentiles: 1%=009ms312.834us; 5%=352ms227.634us; 10%=353ms403.749us; 20%=357ms644.337us; 50%=378ms261.726us; 80%=396ms099.099us; 90%=418ms958.900us; 95%=471ms214.639us; 99%=07s273ms800.081us
Metric: InputOutputAliasCount
  TotalSamples: 3
  Accumulator: 3704.00
  ValueRate: 323.58 / second
  Rate: 0.262081 / second
  Percentiles: 1%=410.00; 5%=410.00; 10%=410.00; 20%=410.00; 50%=1647.00; 80%=1647.00; 90%=1647.00; 95%=1647.00; 99%=1647.00
Metric: IrValueTensorToXlaData
  TotalSamples: 410
  Accumulator: 836ms118.487us
  ValueRate: 01s025ms915.127us / second
  Rate: 502.579 / second
  Percentiles: 1%=751.762us; 5%=872.747us; 10%=937.569us; 20%=001ms040.076us; 50%=001ms302.814us; 80%=002ms723.215us; 90%=003ms551.795us; 95%=004ms827.096us; 99%=007ms478.252us
Metric: OutboundData
  TotalSamples: 551
  Accumulator: 57.37MB
  ValueRate: 1.48MB / second
  Rate: 14.2353 / second
  Percentiles: 1%=2.00B; 5%=2.00B; 10%=2.00B; 20%=8.00B; 50%=512.00B; 80%=32.00KB; 90%=128.00KB; 95%=512.00KB; 99%=772.00KB
Metric: ReleaseDataHandlesTime
  TotalSamples: 6284
  Accumulator: 16s032ms932.787us
  ValueRate: 556ms085.420us / second
  Rate: 244.503 / second
  Percentiles: 1%=366.933us; 5%=396.309us; 10%=413.140us; 20%=441.408us; 50%=530.481us; 80%=710.777us; 90%=871.726us; 95%=001ms138.704us; 99%=005ms501.440us
Metric: TensorsGraphSize
  TotalSamples: 39
  Accumulator: 829432.00
  ValueRate: 22371.14 / second
  Rate: 1.05189 / second
  Percentiles: 1%=2050.00; 5%=20967.00; 10%=21795.00; 20%=21795.00; 50%=21795.00; 80%=21795.00; 90%=21795.00; 95%=21795.00; 99%=21795.00
Metric: TransferToServerTime
  TotalSamples: 551
  Accumulator: 24s744ms467.511us
  ValueRate: 614ms401.430us / second
  Rate: 14.2574 / second
  Percentiles: 1%=763.678us; 5%=890.064us; 10%=965.186us; 20%=001ms074.169us; 50%=001ms401.318us; 80%=003ms502.805us; 90%=007ms464.137us; 95%=326ms873.447us; 99%=360ms933.167us
Metric: TransferToServerTransformTime
  TotalSamples: 551
  Accumulator: 199ms355.684us
  ValueRate: 005ms150.429us / second
  Rate: 14.2353 / second
  Percentiles: 1%=043.856us; 5%=051.417us; 10%=060.698us; 20%=074.467us; 50%=133.422us; 80%=226.977us; 90%=371.772us; 95%=645.010us; 99%=006ms195.709us
Counter: CachedCompile
  Value: 36
Counter: CreateCompileHandles
  Value: 3
Counter: CreateDataHandles
  Value: 63756
Counter: CreateXlaTensor
  Value: 257969
Counter: DestroyDataHandles
  Value: 62408
Counter: DestroyXlaTensor
  Value: 256290
Counter: DeviceDataCacheMiss
  Value: 91
Counter: MarkStep
  Value: 39
Counter: ReleaseDataHandles
  Value: 62408
Counter: UncachedCompile
  Value: 3
Counter: XRTAllocateFromTensor_Empty
  Value: 64
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_copy_from
  Value: 800
Counter: xla::_log_softmax
  Value: 39
Counter: xla::_log_softmax_backward_data
  Value: 39
Counter: xla::_softmax
  Value: 936
Counter: xla::_softmax_backward_data
  Value: 936
Counter: xla::_unsafe_view
  Value: 7722
Counter: xla::add
  Value: 6747
Counter: xla::add_
  Value: 59262
Counter: xla::addcdiv_
  Value: 15912
Counter: xla::addcmul
  Value: 1989
Counter: xla::addcmul_
  Value: 15912
Counter: xla::as_strided
  Value: 410
Counter: xla::bernoulli_
  Value: 2886
Counter: xla::binary_cross_entropy
  Value: 39
Counter: xla::binary_cross_entropy_backward
  Value: 39
Counter: xla::bitwise_not_out
  Value: 39
Counter: xla::bmm
  Value: 5616
Counter: xla::div
  Value: 1950
Counter: xla::div_
  Value: 2886
Counter: xla::embedding
  Value: 234
Counter: xla::embedding_dense_backward
  Value: 234
Counter: xla::empty
  Value: 4619
Counter: xla::empty_strided
  Value: 410
Counter: xla::expand
  Value: 3783
Counter: xla::fill_
  Value: 78
Counter: xla::gelu
  Value: 1014
Counter: xla::gelu_backward
  Value: 1014
Counter: xla::index_select
  Value: 234
Counter: xla::max
  Value: 39
Counter: xla::mm
  Value: 17550
Counter: xla::mul
  Value: 12090
Counter: xla::mul_
  Value: 31824
Counter: xla::native_batch_norm
  Value: 1989
Counter: xla::native_batch_norm_backward
  Value: 1989
Counter: xla::native_layer_norm
  Value: 1989
Counter: xla::native_layer_norm_backward
  Value: 1989
Counter: xla::ne
  Value: 78
Counter: xla::nll_loss_backward
  Value: 39
Counter: xla::nll_loss_forward
  Value: 39
Counter: xla::permute
  Value: 7488
Counter: xla::rsub
  Value: 78
Counter: xla::sigmoid
  Value: 39
Counter: xla::sigmoid_backward
  Value: 39
Counter: xla::slice
  Value: 312
Counter: xla::sqrt
  Value: 15912
Counter: xla::squeeze
  Value: 39
Counter: xla::sub
  Value: 1989
Counter: xla::sum
  Value: 9984
Counter: xla::t
  Value: 23400
Counter: xla::transpose
  Value: 5616
Counter: xla::unsqueeze
  Value: 195
Counter: xla::view
  Value: 68601
Counter: xla::zero_
  Value: 16320
Metric: XrtAllocateFromTensor
  TotalSamples: 86561
  Accumulator: 01m30s807ms609.199us
  Mean: 001ms241.102us
  StdDev: 588.117us
  Rate: 94.0888 / second
  Percentiles: 25%=710.102us; 50%=001ms296.623us; 80%=002ms748.451us; 90%=002ms988.069us; 95%=002ms260.480us; 99%=002ms472.224us
Metric: XrtCompile
  TotalSamples: 144
  Accumulator: 33m09s476ms522.275us
  Mean: 14s816ms802.238us
  StdDev: 26s140ms732.654us
  Rate: 0.0790606 / second
  Percentiles: 25%=010ms833.597us; 50%=140ms220.441us; 80%=48s482ms764.861us; 90%=01m05s198ms743.468us; 95%=01m18s669ms688.016us; 99%=01m18s799ms828.244us
Metric: XrtExecute
  TotalSamples: 8144
  Accumulator: 55m11s830ms869.310us
  Mean: 408ms357.488us
  StdDev: 495ms616.615us
  Rate: 5.27703 / second
  Percentiles: 25%=361ms524.961us; 50%=372ms260.458us; 80%=391ms650.375us; 90%=400ms313.122us; 95%=407ms053.566us; 99%=587ms678.173us
Metric: XrtExecutorEvict
  TotalSamples: 33
  Accumulator: 4.82GB
  Mean: 149.63MB
  StdDev: 98.48MB
  Rate: 0.0256405 / second
  Percentiles: 25%=430.00KB; 50%=215.06MB; 80%=217.84MB; 90%=217.84MB; 95%=217.84MB; 99%=217.84MB
Metric: XrtReleaseAllocation
  TotalSamples: 1325205
  Accumulator: 01m21s789ms740.327us
  Mean: 020.861us
  StdDev: 012.722us
  Rate: 13682 / second
  Percentiles: 25%=012.655us; 50%=017.857us; 80%=027.896us; 90%=036.978us; 95%=045.236us; 99%=072.370us
Metric: XrtTryFreeMemory
  TotalSamples: 13
  Accumulator: 318ms418.367us
  Mean: 024ms493.721us
  StdDev: 004ms520.528us
  Rate: 0.0101009 / second
  Percentiles: 25%=023ms683.906us; 50%=025ms012.235us; 80%=027ms945.682us; 90%=029ms510.977us; 95%=029ms388.376us; 99%=029ms388.376us
```

**Comment by taylanbil** [comment]
If you're already using ParallelLoader, then there's no need to send tensors to device, so you could get rid of that piece of code in the beginning.

Going from `pl.ParallelLoader` to `pl.MpDeviceLoader` won't make a difference in performance.

Looking at the metrics report, the last block of `Metric`'s are the server side metrics, and they don't get reset from one run to the next. So it could belong to a previous run, but in any case, the presence of `XrtTryFreeMemory` suggests that the hbm usage is too big and swapping of tensors from hbm to cpu may be slowing you down. I suggest shrinking the batch size until that metric doesn't appear. As I noted, that metric won't disappear from one run to the next. It only will disappear if you restart tpu.

**Comment by Shiro-LK** [comment]
Thank for you answer, I have removed the `.to(device), `

I reduced the batch size and succeed to make disappear the XrtTryFreeMemory.


Unfortunately it seems still to be slow , my current metric is this one : 
```
###### -- REPORT -- ######
Metric: CompileTime
  TotalSamples: 3
  Accumulator: 02m40s022ms256.329us
  ValueRate: 974ms262.487us / second
  Rate: 0.0292214 / second
  Percentiles: 1%=047ms062.856us; 5%=047ms062.856us; 10%=047ms062.856us; 20%=047ms062.856us; 50%=48s856ms521.707us; 80%=52s120ms671.766us; 90%=52s120ms671.766us; 95%=52s120ms671.766us; 99%=52s120ms671.766us
Metric: DeviceLockWait
  TotalSamples: 135
  Accumulator: 620.517us
  ValueRate: 003.750us / second
  Rate: 0.815917 / second
  Percentiles: 1%=003.188us; 5%=003.324us; 10%=003.457us; 20%=003.688us; 50%=004.439us; 80%=005.195us; 90%=005.705us; 95%=006.076us; 99%=010.267us
Metric: ExecuteTime
  TotalSamples: 135
  Accumulator: 30s142ms946.868us
  ValueRate: 182ms054.917us / second
  Rate: 0.815389 / second
  Percentiles: 1%=199ms658.958us; 5%=202ms054.224us; 10%=203ms317.476us; 20%=209ms892.102us; 50%=224ms112.850us; 80%=235ms819.125us; 90%=244ms590.828us; 95%=248ms277.699us; 99%=315ms932.109us
Metric: InputOutputAliasCount
  TotalSamples: 3
  Accumulator: 3704.00
  ValueRate: 73.30 / second
  Rate: 0.0593717 / second
  Percentiles: 1%=410.00; 5%=410.00; 10%=410.00; 20%=410.00; 50%=1647.00; 80%=1647.00; 90%=1647.00; 95%=1647.00; 99%=1647.00
Metric: IrValueTensorToXlaData
  TotalSamples: 410
  Accumulator: 814ms628.165us
  ValueRate: 01s017ms759.076us / second
  Rate: 512.361 / second
  Percentiles: 1%=708.928us; 5%=772.897us; 10%=825.578us; 20%=898.197us; 50%=001ms184.526us; 80%=002ms623.331us; 90%=002ms438.444us; 95%=004ms481.584us; 99%=013ms436.456us
Metric: OutboundData
  TotalSamples: 863
  Accumulator: 62.27MB
  ValueRate: 382.11KB / second
  Rate: 5.17168 / second
  Percentiles: 1%=2.00B; 5%=2.00B; 10%=2.00B; 20%=2.00B; 50%=128.00B; 80%=8.00KB; 90%=128.00KB; 95%=386.00KB; 99%=512.00KB
Metric: ReleaseDataHandlesTime
  TotalSamples: 20701
  Accumulator: 29s970ms257.277us
  ValueRate: 460ms937.073us / second
  Rate: 299.545 / second
  Percentiles: 1%=367.619us; 5%=398.778us; 10%=423.086us; 20%=460.667us; 50%=654.556us; 80%=942.036us; 90%=001ms179.335us; 95%=002ms561.522us; 99%=003ms110.088us
Metric: TensorsGraphSize
  TotalSamples: 135
  Accumulator: 2921752.00
  ValueRate: 17669.94 / second
  Rate: 0.816442 / second
  Percentiles: 1%=20967.00; 5%=21795.00; 10%=21795.00; 20%=21795.00; 50%=21795.00; 80%=21795.00; 90%=21795.00; 95%=21795.00; 99%=21795.00
Metric: TransferToServerTime
  TotalSamples: 863
  Accumulator: 31s394ms938.074us
  ValueRate: 188ms181.395us / second
  Rate: 5.17299 / second
  Percentiles: 1%=731.648us; 5%=819.915us; 10%=894.466us; 20%=001ms048.871us; 50%=002ms540.277us; 80%=007ms785.227us; 90%=181ms483.726us; 95%=194ms312.493us; 99%=212ms278.444us
Metric: TransferToServerTransformTime
  TotalSamples: 863
  Accumulator: 209ms933.641us
  ValueRate: 001ms252.071us / second
  Rate: 5.17168 / second
  Percentiles: 1%=038.647us; 5%=042.254us; 10%=048.370us; 20%=062.332us; 50%=116.621us; 80%=183.603us; 90%=238.864us; 95%=628.669us; 99%=003ms615.766us
Counter: CachedCompile
  Value: 132
Counter: CreateCompileHandles
  Value: 3
Counter: CreateDataHandles
  Value: 222636
Counter: CreateXlaTensor
  Value: 888881
Counter: DestroyDataHandles
  Value: 221251
Counter: DestroyXlaTensor
  Value: 887202
Counter: DeviceDataCacheMiss
  Value: 283
Counter: MarkStep
  Value: 135
Counter: ReleaseDataHandles
  Value: 221251
Counter: UncachedCompile
  Value: 3
Counter: XRTAllocateFromTensor_Empty
  Value: 63
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 10
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_copy_from
  Value: 1760
Counter: xla::_log_softmax
  Value: 135
Counter: xla::_log_softmax_backward_data
  Value: 135
Counter: xla::_softmax
  Value: 3240
Counter: xla::_softmax_backward_data
  Value: 3240
Counter: xla::_unsafe_view
  Value: 26730
Counter: xla::add
  Value: 23355
Counter: xla::add_
  Value: 206142
Counter: xla::addcdiv_
  Value: 55080
Counter: xla::addcmul
  Value: 6885
Counter: xla::addcmul_
  Value: 55080
Counter: xla::as_strided
  Value: 410
Counter: xla::bernoulli_
  Value: 9990
Counter: xla::binary_cross_entropy
  Value: 135
Counter: xla::binary_cross_entropy_backward
  Value: 135
Counter: xla::bitwise_not_out
  Value: 135
Counter: xla::bmm
  Value: 19440
Counter: xla::div
  Value: 6750
Counter: xla::div_
  Value: 9990
Counter: xla::embedding
  Value: 810
Counter: xla::embedding_dense_backward
  Value: 810
Counter: xla::empty
  Value: 12971
Counter: xla::empty_strided
  Value: 410
Counter: xla::expand
  Value: 13095
Counter: xla::fill_
  Value: 270
Counter: xla::gelu
  Value: 3510
Counter: xla::gelu_backward
  Value: 3510
Counter: xla::index_select
  Value: 810
Counter: xla::max
  Value: 135
Counter: xla::mm
  Value: 60750
Counter: xla::mul
  Value: 41850
Counter: xla::mul_
  Value: 110160
Counter: xla::native_batch_norm
  Value: 6885
Counter: xla::native_batch_norm_backward
  Value: 6885
Counter: xla::native_layer_norm
  Value: 6885
Counter: xla::native_layer_norm_backward
  Value: 6885
Counter: xla::ne
  Value: 270
Counter: xla::nll_loss_backward
  Value: 135
Counter: xla::nll_loss_forward
  Value: 135
Counter: xla::permute
  Value: 25920
Counter: xla::rsub
  Value: 270
Counter: xla::sigmoid
  Value: 135
Counter: xla::sigmoid_backward
  Value: 135
Counter: xla::slice
  Value: 1080
Counter: xla::sqrt
  Value: 55080
Counter: xla::squeeze
  Value: 135
Counter: xla::sub
  Value: 6885
Counter: xla::sum
  Value: 34560
Counter: xla::t
  Value: 81000
Counter: xla::transpose
  Value: 19440
Counter: xla::unsqueeze
  Value: 675
Counter: xla::view
  Value: 237465
Counter: xla::zero_
  Value: 55488
Metric: XrtAllocateFromTensor
  TotalSamples: 21816
  Accumulator: 21s633ms548.614us
  Mean: 001ms136.030us
  StdDev: 557.136us
  Rate: 136.85 / second
  Percentiles: 25%=669.597us; 50%=001ms223.373us; 80%=002ms527.374us; 90%=002ms680.071us; 95%=002ms804.433us; 99%=002ms437.020us
Metric: XrtCompile
  TotalSamples: 48
  Accumulator: 24m20s607ms166.260us
  Mean: 30s408ms482.630us
  StdDev: 22s166ms539.056us
  Rate: 0.135121 / second
  Percentiles: 25%=009ms568.338us; 50%=44s577ms684.551us; 80%=50s694ms164.049us; 90%=52s858ms219.847us; 95%=52s874ms986.775us; 99%=52s932ms648.726us
Metric: XrtExecute
  TotalSamples: 1816
  Accumulator: 06m36s633ms634.607us
  Mean: 221ms578.490us
  StdDev: 016ms535.296us
  Rate: 16.9836 / second
  Percentiles: 25%=208ms924.889us; 50%=220ms907.111us; 80%=235ms594.985us; 90%=241ms246.372us; 95%=247ms266.683us; 99%=259ms299.727us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReleaseAllocation
  TotalSamples: 283357
  Accumulator: 21s837ms266.781us
  Mean: 071.396us
  StdDev: 193.882us
  Rate: 7805.42 / second
  Percentiles: 25%=015.381us; 50%=025.064us; 80%=064.344us; 90%=131.119us; 95%=248.770us; 99%=001ms058.086us
```
