### ISSUE TITLE
Beam Search Compiles Frequently

### ISSUE THREAD

**Issue by jfrankle** [pytorch/xla#2757]
## ❓ Questions and Help

I'm trying to implement beam search for the autoregressive predictions of a transformer that I have implemented. Although I've tried my best to ensure everything has constant sizes, I have struggled with frequent compilation. The code is below. The model is already in eval mode and the model code itself runs smoothly in torch_xla (a version of this code with a single beam runs fine).

```
def predict(model, input, input_mask, bos_value, beam_size=4):
    X = source.size(0) # The batch size.
    Y = beam_size # The size of the beam to maintain.
    Z = source.size(1) # The length of each input/output sentence.
    V = 32000 # The fixed output vocabulary size.

    # Create tensors to store the results.
    prediction = torch.zeros([X * Y, Z]).long().to(source.device) # Will store the output sentences for each beam.
    prediction[:, 0] = bos_value # Set the first token in each sentence to the BOS value.
    log_probabilities = torch.zeros([X*Y]).to(source.device) # The log probabilities associated with each beam.

    # Repeat each input sentence for each beam.
    source = source.reshape([X, 1, Z]).repeat([1, Y, 1]).reshape([X*Y, Z])
    source_mask = source_mask.reshape([X, 1, Z]).repeat([1, Y, 1]).reshape([X*Y, Z])

    # Useful for later. If Y = 4, has value: [0, 0, 0, 0, 4, 4, 4, 4, 8, 8, 8, 8, ...]
    offset = torch.arange(X).reshape([-1, 1]).repeat(1, Y).reshape(-1) * Y
 
    # Make the predictions.
    for i in range(Z-1):
        # Compute the output.
        prediction_mask[:, i] = 1 # Make the next token of the prediction available to attend over.
        output = model.forward([source, source_mask, prediction, prediction_mask]) # Shape: [X*Y, V].

        # Compute the log probabilities of each element in the beam.
        output_probabilities = (output[:, i] + log_probabilities.view([-1, 1])).reshape([X, Y*V]) # Shape: [X, Y*V]
        if i == 0: output = output[:, :V] # The first token is always the same, so the output will otherwise be repetitive.

        # Determine the most probable next choices.
        top = torch.topk(output, Y, dim=1) # Shape: [X, Y]
        existing_beams = top.indices // V # The existing beams that begin those most probable next choices.
        new_tokens = top.indices % V # The index of the new token to add to those beams.

        # Construct the new beams.
        prediction = prediction[existing_beams.view(-1) + offset] # Select the existing beams.
        prediction[:, i+1] = new_tokens.view(-1) # Add the new tokens

        # Update the probabilities.
        log_probabilities.add_(top.values.view(-1))

    # Extract the most probable beams.
    top_beams = torch.argmax(log_probabilities.view([X, Y]), dim=1)
    offsets = torch.arange(X) * Y
    return prediction[top_beams + offsets]
```

The metric report from five steps of this is below:

```
    Prediction: *****Metric: CompileTime
  TotalSamples: 11
  Accumulator: 01m23s803ms422.836us
  ValueRate: 828ms688.149us / second
  Rate: 0.109954 / second
  Percentiles: 1%=040ms636.520us; 5%=040ms636.520us; 10%=01s107ms064.012us; 20%=04s038ms795.832us; 50%=09s804ms440.315us; 80%=11s390ms466.737us; 90%=12s109ms947.607us; 95%=13s076ms505.473us; 99%=13s076ms505.473us
Metric: DeviceLockWait
  TotalSamples: 11
  Accumulator: 034.993us
  ValueRate: 000.393us / second
  Rate: 0.123512 / second
  Percentiles: 1%=001.599us; 5%=001.599us; 10%=001.766us; 20%=001.797us; 50%=002.943us; 80%=003.493us; 90%=004.061us; 95%=007.762us; 99%=007.762us
Metric: ExecuteTime
  TotalSamples: 11
  Accumulator: 02s772ms842.672us
  ValueRate: 018ms658.963us / second
  Rate: 0.109631 / second
  Percentiles: 1%=021ms478.352us; 5%=021ms478.352us; 10%=044ms164.267us; 20%=085ms797.765us; 50%=139ms685.548us; 80%=258ms748.712us; 90%=267ms445.697us; 95%=319ms433.236us; 99%=319ms433.236us
Metric: InboundData
  TotalSamples: 9
  Accumulator: 202.50KB
  ValueRate: 2.53KB / second
  Rate: 0.112326 / second
  Percentiles: 1%=512.00B; 5%=512.00B; 10%=512.00B; 20%=512.00B; 50%=512.00B; 80%=50.00KB; 90%=50.00KB; 95%=50.00KB; 99%=50.00KB
Metric: InputOutputAliasCount
  TotalSamples: 7
  Accumulator: 797.00
  ValueRate: 8.95 / second
  Rate: 0.0786196 / second
  Percentiles: 1%=1.00; 5%=1.00; 10%=1.00; 20%=1.00; 50%=1.00; 80%=5.00; 90%=787.00; 95%=787.00; 99%=787.00
Metric: IrValueTensorToXlaData
  TotalSamples: 1061
  Accumulator: 09s487ms256.286us
  ValueRate: 052ms899.440us / second
  Rate: 5.69621 / second
  Percentiles: 1%=001ms042.001us; 5%=001ms189.338us; 10%=001ms297.552us; 20%=001ms437.674us; 50%=002ms963.805us; 80%=005ms954.075us; 90%=011ms726.565us; 95%=016ms871.947us; 99%=288ms769.364us
Metric: OutboundData
  TotalSamples: 1071
  Accumulator: 1.70GB
  ValueRate: 9.50MB / second
  Rate: 5.69735 / second
  Percentiles: 1%=512.00B; 5%=2.00KB; 10%=2.00KB; 20%=2.00KB; 50%=2.00KB; 80%=1.00MB; 90%=4.00MB; 95%=4.00MB; 99%=70.94MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 281
  Accumulator: 575ms740.201us
  ValueRate: 005ms260.194us / second
  Rate: 2.5718 / second
  Percentiles: 1%=571.145us; 5%=681.513us; 10%=739.648us; 20%=820.757us; 50%=001ms015.607us; 80%=002ms812.339us; 90%=003ms018.199us; 95%=004ms299.669us; 99%=024ms343.664us
Metric: TensorsGraphSize
  TotalSamples: 11
  Accumulator: 61970.00
  ValueRate: 619.42 / second
  Rate: 0.109951 / second
  Percentiles: 1%=20.00; 5%=20.00; 10%=2496.00; 20%=2529.00; 50%=4743.00; 80%=9138.00; 90%=9171.00; 95%=11352.00; 99%=11352.00
Metric: TransferFromServerTime
  TotalSamples: 9
  Accumulator: 029ms168.445us
  ValueRate: 364.043us / second
  Rate: 0.112326 / second
  Percentiles: 1%=002ms747.399us; 5%=002ms747.399us; 10%=002ms747.399us; 20%=002ms877.194us; 50%=003ms614.258us; 80%=005ms678.448us; 90%=006ms914.211us; 95%=006ms914.211us; 99%=006ms914.211us
Metric: TransferToServerTime
  TotalSamples: 1071
  Accumulator: 10s556ms230.812us
  ValueRate: 052ms110.604us / second
  Rate: 5.69737 / second
  Percentiles: 1%=001ms034.786us; 5%=001ms182.423us; 10%=001ms291.195us; 20%=001ms437.799us; 50%=002ms967.639us; 80%=005ms977.170us; 90%=011ms967.013us; 95%=016ms168.439us; 99%=288ms752.701us
Metric: TransferToServerTransformTime
  TotalSamples: 1071
  Accumulator: 759ms218.845us
  ValueRate: 004ms108.685us / second
  Rate: 5.69735 / second
  Percentiles: 1%=092.899us; 5%=105.086us; 10%=114.922us; 20%=128.788us; 50%=174.396us; 80%=406.318us; 90%=001ms047.167us; 95%=001ms217.898us; 99%=016ms157.652us
Counter: CreateCompileHandles
  Value: 11
Counter: CreateDataHandles
  Value: 1929
Counter: CreateXlaTensor
  Value: 8987
Counter: DestroyDataHandles
  Value: 1061
Counter: DestroyXlaTensor
  Value: 8115
Counter: DeviceDataCacheMiss
  Value: 7
Counter: MarkStep
  Value: 2
Counter: ReleaseDataHandles
  Value: 1061
Counter: UncachedCompile
  Value: 11
Counter: XRTAllocateFromTensor_Empty
  Value: 44
Counter: XrtCompile_Empty
  Value: 96
Counter: XrtExecuteChained_Empty
  Value: 96
Counter: XrtExecute_Empty
  Value: 96
Counter: XrtMemoryInfo_Empty
  Value: 96
Counter: XrtRead_Empty
  Value: 96
Counter: XrtReleaseAllocationHandle_Empty
  Value: 96
Counter: XrtReleaseCompileHandle_Empty
  Value: 96
Counter: XrtSessionCount
  Value: 7
Counter: XrtSubTuple_Empty
  Value: 96
Counter: aten::floor_divide
  Value: 5
Counter: xla::_copy_from
  Value: 1076
Counter: xla::_log_softmax
  Value: 7
Counter: xla::_s_where
  Value: 2
Counter: xla::_softmax
  Value: 108
Counter: xla::_unsafe_view
  Value: 798
Counter: xla::add
  Value: 202
Counter: xla::add_
  Value: 591
Counter: xla::addcmul
  Value: 192
Counter: xla::as_strided
  Value: 799
Counter: xla::bmm
  Value: 216
Counter: xla::clone
  Value: 119
Counter: xla::div
  Value: 109
Counter: xla::embedding
  Value: 12
Counter: xla::empty
  Value: 809
Counter: xla::empty_strided
  Value: 799
Counter: xla::eq
  Value: 118
Counter: xla::exp
  Value: 1
Counter: xla::expand
  Value: 672
Counter: xla::fill_
  Value: 9
Counter: xla::index
  Value: 5
Counter: xla::index_select
  Value: 12
Counter: xla::kl_div
  Value: 1
Counter: xla::log_
  Value: 1
Counter: xla::masked_fill_
  Value: 115
Counter: xla::mm
  Value: 582
Counter: xla::mul
  Value: 16
Counter: xla::native_batch_norm
  Value: 192
Counter: xla::native_layer_norm
  Value: 192
Counter: xla::ne
  Value: 2
Counter: xla::permute
  Value: 4
Counter: xla::relu
  Value: 72
Counter: xla::remainder
  Value: 5
Counter: xla::repeat
  Value: 2
Counter: xla::scatter_
  Value: 1
Counter: xla::select
  Value: 16
Counter: xla::slice
  Value: 44
Counter: xla::squeeze
  Value: 3
Counter: xla::sub
  Value: 1
Counter: xla::sum
  Value: 4
Counter: xla::t
  Value: 582
Counter: xla::topk
  Value: 7
Counter: xla::transpose
  Value: 540
Counter: xla::unsqueeze
  Value: 230
Counter: xla::view
  Value: 2696
Counter: xla::zero_
  Value: 1
Metric: XrtAllocateFromTensor
  TotalSamples: 11118
  Accumulator: 19s578ms422.802us
  Mean: 005ms042.732us
  StdDev: 017ms109.313us
  Rate: 9.71897 / second
  Percentiles: 25%=518.142us; 50%=001ms044.825us; 80%=002ms420.003us; 90%=004ms512.193us; 95%=008ms549.875us; 99%=107ms798.096us
Metric: XrtCompile
  TotalSamples: 88
  Accumulator: 11m04s862ms380.350us
  Mean: 08s544ms890.686us
  StdDev: 04s036ms740.130us
  Rate: 0.879578 / second
  Percentiles: 25%=04s005ms330.640us; 50%=09s738ms592.735us; 80%=11s326ms538.196us; 90%=12s064ms490.316us; 95%=13s983ms542.936us; 99%=13s001ms770.339us
Metric: XrtExecute
  TotalSamples: 87
  Accumulator: 13s565ms282.128us
  Mean: 144ms428.530us
  StdDev: 093ms757.369us
  Rate: 0.867072 / second
  Percentiles: 25%=077ms145.871us; 50%=130ms071.776us; 80%=243ms469.386us; 90%=263ms152.700us; 95%=296ms072.027us; 99%=318ms654.997us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReadLiteral
  TotalSamples: 71
  Accumulator: 061ms402.945us
  Mean: 864.830us
  StdDev: 280.906us
  Rate: 0.886149 / second
  Percentiles: 25%=632.712us; 50%=863.715us; 80%=001ms167.664us; 90%=001ms217.972us; 95%=001ms300.725us; 99%=001ms332.199us
Metric: XrtReleaseAllocation
  TotalSamples: 2273
  Accumulator: 038ms711.625us
  Mean: 020.804us
  StdDev: 073.373us
  Rate: 9.32549 / second
  Percentiles: 25%=006.985us; 50%=008.689us; 80%=015.013us; 90%=032.275us; 95%=043.363us; 99%=268.940us
```

I suspect that some of the dynamic operations (like `topk` and selecting the new beams) could be culprits, as could the fact that there are dependencies between loop iterations that could lead to a giant computation graph. Thus far, though, I have not been able to successfully address these issues.

I'd greatly appreciate any help in figuring this out. Thank you so much!

Jonathan

**Comment by jysohn23** [comment]
Hi @jfrankle, so from this I see two problems:
* Unlowered op `aten::floor_divide`
* XLATensors being used for indexing:
  * `prediction = prediction[existing_beams.view(-1) + offset]`
  * `prediction[top_beams + offsets]`

For the indexing parts, using XLATensors as index causes the actual values for those tensors to be evaluated causing a compilation. Also could you run https://github.com/pytorch/xla/blob/master/TROUBLESHOOTING.md#using-debug_runpy-to-collect-debug-information for more debug info for us?

Not sure how helpful, but dropping this TPU friendly beam search implementation in TF in case it's helpful: https://github.com/tensorflow/models/blob/master/official/nlp/modeling/ops/beam_search.py

**Comment by jfrankle** [comment]
Hi Daniel -

This is incredibly helpful. I had trouble getting the debugging information to collect properly, but I did make a few fixes based on your suggestions:
* I replaced the `//` operator with `/` and then `.long()` (which has the same effect).
* I replaced the indexing with a for-loop with several `torch.where` statements since there are a small, discrete number of possible values that can be used for indexing.

There is still one interesting issue: if I run the code it runs quickly for the first 40 or 50 loop iterations, after which it hangs indefinitely. Do you have any thoughts about what might be going on?

Thank you for the (very prompt) help!

Jonathan

**Comment by jysohn23** [comment]
Do you happen to have a similar metrics report as your original post? That'd be helpful to get a glimpse of what's going on.

**Comment by jfrankle** [comment]
And below is the report as of the step where computation hangs:

```
Metric: CompileTime
  TotalSamples: 2
  Accumulator: 095ms182.874us
  ValueRate: 006ms859.261us / second
  Rate: 0.123116 / second
  Percentiles: 1%=034ms096.803us; 5%=034ms096.803us; 10%=034ms096.803us; 20%=034ms096.803us; 50%=061ms086.071us; 80%=061ms086.071us; 90%=061ms086.071us; 95%=061ms086.071us; 99%=061ms086.071us
Metric: DeviceLockWait
  TotalSamples: 2
  Accumulator: 013.884us
  ValueRate: 000.843us / second
  Rate: 0.121458 / second
  Percentiles: 1%=006.416us; 5%=006.416us; 10%=006.416us; 20%=006.416us; 50%=007.468us; 80%=007.468us; 90%=007.468us; 95%=007.468us; 99%=007.468us
Metric: ExecuteTime
  TotalSamples: 2
  Accumulator: 054ms544.227us
  ValueRate: 003ms295.349us / second
  Rate: 0.123089 / second
  Percentiles: 1%=020ms618.221us; 5%=020ms618.221us; 10%=020ms618.221us; 20%=020ms618.221us; 50%=034ms926.006us; 80%=034ms926.006us; 90%=034ms926.006us; 95%=034ms926.006us; 99%=034ms926.006us
Metric: InputOutputAliasCount
  TotalSamples: 2
  Accumulator: 792.00
  ValueRate: 48.58 / second
  Rate: 0.122688 / second
  Percentiles: 1%=5.00; 5%=5.00; 10%=5.00; 20%=5.00; 50%=787.00; 80%=787.00; 90%=787.00; 95%=787.00; 99%=787.00
Metric: IrValueTensorToXlaData
  TotalSamples: 1046
  Accumulator: 09s190ms378.578us
  ValueRate: 142ms861.854us / second
  Rate: 16.0037 / second
  Percentiles: 1%=001ms017.648us; 5%=001ms104.393us; 10%=001ms180.533us; 20%=001ms292.095us; 50%=002ms711.441us; 80%=005ms558.601us; 90%=011ms142.159us; 95%=013ms788.887us; 99%=321ms302.436us
Metric: OutboundData
  TotalSamples: 1056
  Accumulator: 1.70GB
  ValueRate: 26.87MB / second
  Rate: 16.0044 / second
  Percentiles: 1%=2.00KB; 5%=2.00KB; 10%=2.00KB; 20%=2.00KB; 50%=2.00KB; 80%=1.00MB; 90%=4.00MB; 95%=4.00MB; 99%=70.94MB
Metric: ReleaseDataHandlesTime
  TotalSamples: 270
  Accumulator: 630ms501.987us
  ValueRate: 079ms319.269us / second
  Rate: 34.0209 / second
  Percentiles: 1%=531.800us; 5%=574.067us; 10%=590.709us; 20%=649.254us; 50%=805.718us; 80%=001ms089.152us; 90%=001ms335.022us; 95%=008ms150.407us; 99%=055ms869.607us
Metric: TensorsGraphSize
  TotalSamples: 2
  Accumulator: 3950.00
  ValueRate: 243.18 / second
  Rate: 0.123128 / second
  Percentiles: 1%=20.00; 5%=20.00; 10%=20.00; 20%=20.00; 50%=3930.00; 80%=3930.00; 90%=3930.00; 95%=3930.00; 99%=3930.00
Metric: TransferToServerTime
  TotalSamples: 1056
  Accumulator: 09s271ms467.399us
  ValueRate: 143ms542.095us / second
  Rate: 16.0049 / second
  Percentiles: 1%=001ms009.509us; 5%=001ms093.714us; 10%=001ms170.081us; 20%=001ms281.715us; 50%=002ms706.633us; 80%=005ms568.710us; 90%=011ms145.058us; 95%=013ms784.405us; 99%=321ms286.655us
Metric: TransferToServerTransformTime
  TotalSamples: 1056
  Accumulator: 827ms517.035us
  ValueRate: 013ms658.969us / second
  Rate: 16.0044 / second
  Percentiles: 1%=090.776us; 5%=104.203us; 10%=111.594us; 20%=123.871us; 50%=176.938us; 80%=486.159us; 90%=001ms352.916us; 95%=002ms556.122us; 99%=016ms716.026us
Counter: CreateCompileHandles
  Value: 2
Counter: CreateDataHandles
  Value: 1905
Counter: CreateXlaTensor
  Value: 57356
Counter: DestroyDataHandles
  Value: 1044
Counter: DestroyXlaTensor
  Value: 56480
Counter: DeviceDataCacheMiss
  Value: 7
Counter: MarkStep
  Value: 2
Counter: ReleaseDataHandles
  Value: 1044
Counter: UncachedCompile
  Value: 2
Counter: XRTAllocateFromTensor_Empty
  Value: 42
Counter: XrtCompile_Empty
  Value: 128
Counter: XrtExecuteChained_Empty
  Value: 128
Counter: XrtExecute_Empty
  Value: 128
Counter: XrtMemoryInfo_Empty
  Value: 128
Counter: XrtRead_Empty
  Value: 128
Counter: XrtReleaseAllocationHandle_Empty
  Value: 128
Counter: XrtReleaseCompileHandle_Empty
  Value: 128
Counter: XrtSessionCount
  Value: 9
Counter: XrtSubTuple_Empty
  Value: 128
Counter: xla::_copy_from
  Value: 1189
Counter: xla::_log_softmax
  Value: 46
Counter: xla::_s_where
  Value: 178
Counter: xla::_softmax
  Value: 810
Counter: xla::_unsafe_view
  Value: 5985
Counter: xla::add
  Value: 1484
Counter: xla::add_
  Value: 4413
Counter: xla::addcmul
  Value: 1440
Counter: xla::as_strided
  Value: 794
Counter: xla::bmm
  Value: 1620
Counter: xla::clone
  Value: 816
Counter: xla::div
  Value: 855
Counter: xla::embedding
  Value: 90
Counter: xla::empty
  Value: 932
Counter: xla::empty_strided
  Value: 794
Counter: xla::eq
  Value: 996
Counter: xla::exp
  Value: 1
Counter: xla::expand
  Value: 5451
Counter: xla::fill_
  Value: 48
Counter: xla::index_select
  Value: 90
Counter: xla::kl_div
  Value: 1
Counter: xla::log_
  Value: 1
Counter: xla::masked_fill_
  Value: 817
Counter: xla::mm
  Value: 4365
Counter: xla::mul
  Value: 94
Counter: xla::native_batch_norm
  Value: 1440
Counter: xla::native_layer_norm
  Value: 1440
Counter: xla::ne
  Value: 2
Counter: xla::permute
  Value: 4
Counter: xla::relu
  Value: 540
Counter: xla::remainder
  Value: 44
Counter: xla::repeat
  Value: 178
Counter: xla::scatter_
  Value: 1
Counter: xla::select
  Value: 133
Counter: xla::slice
  Value: 493
Counter: xla::squeeze
  Value: 3
Counter: xla::sub
  Value: 1
Counter: xla::sum
  Value: 4
Counter: xla::t
  Value: 4365
Counter: xla::topk
  Value: 46
Counter: xla::transpose
  Value: 4050
Counter: xla::unsqueeze
  Value: 1634
Counter: xla::view
  Value: 20383
Counter: xla::zero_
  Value: 46
Metric: XrtAllocateFromTensor
  TotalSamples: 26712
  Accumulator: 45s176ms674.205us
  Mean: 005ms068.751us
  StdDev: 018ms527.405us
  Rate: 50.0525 / second
  Percentiles: 25%=468.902us; 50%=001ms077.632us; 80%=002ms009.276us; 90%=003ms545.405us; 95%=012ms787.418us; 99%=105ms727.423us
Metric: XrtCompile
  TotalSamples: 48
  Accumulator: 15s917ms472.521us
  Mean: 311ms780.678us
  StdDev: 686ms010.972us
  Rate: 0.0882551 / second
  Percentiles: 25%=176.018us; 50%=010ms261.345us; 80%=016ms829.779us; 90%=02s811ms993.520us; 95%=02s983ms715.917us; 99%=02s122ms505.164us
Metric: XrtExecute
  TotalSamples: 48
  Accumulator: 364ms229.695us
  Mean: 008ms588.119us
  StdDev: 006ms855.428us
  Rate: 0.0882537 / second
  Percentiles: 25%=002ms743.636us; 50%=012ms619.409us; 80%=014ms730.161us; 90%=014ms023.413us; 95%=015ms557.074us; 99%=016ms289.638us
Metric: XrtExecutorEvict
  TotalSamples: 0
  Accumulator: nanB
  Mean: nanB
  StdDev: nanB
  Percentiles: 
Metric: XrtReleaseAllocation
  TotalSamples: 6574
  Accumulator: 176ms046.174us
  Mean: 035.161us
  StdDev: 141.690us
  Rate: 129.235 / second
  Percentiles: 25%=013.697us; 50%=016.571us; 80%=023.769us; 90%=033.060us; 95%=051.408us; 99%=454.033us
```
