### ISSUE TITLE
Running PyTorch with Cloud TPU on Google Kubernetes Engine

### ISSUE THREAD

**Issue by nicholasbreckwoldt** [pytorch/xla#3921]
## ❓ Questions and Help

I am investigating running PyTorch with Cloud TPU using GKE on Google Cloud. Currently, I am having to manually create a TPU Pod via the UI, retrieve and populate the TPU's internal IP into XRT_TPU_CONFIG env and then run the following GKE batch/v1 job spec, which works!

```
apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-tpu-xla-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pytorch-xla
        image: ${IMAGE}
        env:
          - name: XRT_TPU_CONFIG
            value: tpu_worker;${TPU_INTERNAL_IP}:8470
```

Ideally, I'd like to automatically provision the TPU together with the GKE job spec as below (this is how one would currently do it when running TensorFlow on TPU) so that GKE takes care of provisioning and tear-down, etc for me. However, in this case I do not know the TPU_INTERNAL_IP beforehand. If I run the below, the job throws an error due to the missing/invalid XRT_TPU_CONFIG env variable.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-tpu-xla-test
spec:
  template:
     metadata:
       annotations:
         tf-version.cloud-tpus.google.com: pytorch-1.12
    spec:
      restartPolicy: Never
      containers:
      - name: pytorch-xla
        image: ${MY_IMAGE}
        env:
           - name: XRT_TPU_CONFIG
             value: tpu_worker;${TPU_INTERNAL_IP}:8470   # NOT KNOWN BEFORE HAND
       resources:
         limits:
            cloud-tpus.google.com/preemptible-v2: 8
```

Is there a way to instruct GKE in the spec to automatically populate the XRT_TPU_CONFIG env with TPU_INTERNAL_IP address once it is available, given that GKE is provisioning the TPU itself?
